local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig()
    return {
        global = {
            font = "DorisPP",
            
            refreshDelay = 0.1,

            manaColor = "2482ff",
            rageColor = "ff0000",
            focusColor = "ff8000",
            energyColor = "ffff00",
            runicPowerColor = "00d4ff",
            lunarPowerColor = "4d85e6",
            comboPointColor = "ffaa00",
            runesColor = "00d4ff",

            hostileColor = "ff0000",
            neutralColor = "ffff00",
            friendlyColor = "00ff00",

            highlightColor = "ffbb00",

            castbarColor = "ffbb00",
            castbarChannelColor = "ffbb00",
            castbarNonInterruptibleColor = "888888",
            castbarEmpowerColor = "5588dd",

            dispelColors = {
                Magic   = "ff00ffFF",
                Curse   = "990099ff",
                Disease = "bbcc00FF",
                Poison  = "00cc00FF",
                Bleed   = "CC0000FF",
                Enrage  = "FF3300FF",
                default = "FFFFFFFF",
            },

            dispelTextures = {
                Magic   = "icons_64x64_magic",
                Curse   = "icons_64x64_curse",
                Disease = "icons_64x64_disease",
                Poison  = "icons_64x64_poison",
                Bleed   = "icons_64x64_bleed",
                Enrage  = "icons_64x64_enrage",
                default = "icons_64x64_deadly",
            },

            roleIcons = {
                TANK = "RaidFrame-Icon-MainTank",
                HEALER = "icons_64x64_heal",
                DAMAGER = "RaidFrame-Icon-MainAssist",
            },

            specAbbrevById = {
                -- Warrior
                [71] = "ARMS",
                [72] = "FURY",
                [73] = "PROT",
                -- Paladin
                [65] = "HOLY",
                [66] = "PROT",
                [70] = "RET",
                -- Hunter
                [253] = "BM",
                [254] = "MM",
                [255] = "SV",
                -- Rogue
                [259] = "ASSA",
                [260] = "OUTL",
                [261] = "SUB",
                -- Priest
                [256] = "DISC",
                [257] = "HOLY",
                [258] = "SPRIEST",
                -- Death Knight
                [250] = "BDK",
                [251] = "FDK",
                [252] = "UDK",
                -- Shaman
                [262] = "ELE",
                [263] = "ENH",
                [264] = "RESTO",
                -- Mage
                [62] = "ARC",
                [63] = "FIRE",
                [64] = "FROST",
                -- Warlock
                [265] = "AFF",
                [266] = "DEMO",
                [267] = "DESTRO",
                -- Monk
                [268] = "BREW",
                [269] = "WW",
                [270] = "MW",
                -- Druid
                [102] = "BAL",
                [103] = "FERAL",
                [104] = "GUARD",
                [105] = "RESTO",
                -- Demon Hunter
                [577] = "HAVOC",
                [581] = "VENG",
                -- Evoker
                [1467] = "DEV",
                [1468] = "PRES",
                [1473] = "AUG",
            },
        },
        player = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfPlayerFrame",
            anchor = "TOPRIGHT",
            relativeTo = "UIParent",
            relativePoint = "BOTTOM",
            offsetX = -178,
            offsetY = 163,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",

            modules = {
                health = {
                    enabled = true,
                    frameName = "zfPlayerHealthbar",
                    anchor = "TOP",
                    relativeTo = "zfPlayerFrame",
                    relativePoint = "TOP",
                    texture = "smooth",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "zfPlayerFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                    },
                    {
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "zfPlayerFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                    },
                },
                power = {
                    enabled = true,
                    frameName = "zfPlayerPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "zfPlayerFrame",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                castbar = {
                    enabled = true,
                    frameName = "zfPlayerCastbar",
                    anchor = "BOTTOM",
                    relativeTo = "MainActionBar",
                    relativePoint = "TOP",
                    width = 332,
                    height = 30,
                    offsetX = 0,
                    offsetY = 10,
                    texture = "smooth",
                    showSpellName = true,
                    textAlignment = "CENTER",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 2,
                    borderColor = "000000FF",
                },
                auraFilters = {
                    {
                        name = "StaticPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        disableMouse = false,
                        frameName = "zfStaticPlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = -100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActivePlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = false,
                        frameName = "zfActivePlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "zfStaticPlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActivePlayerDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "zfActivePlayerDebuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "zfActivePlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "FF0000FF",
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    texture = "Diagonal",
                },
                combatIndicator = {
                    enabled = true,
                    atlasTexture = "titleprestige-prestigeicon",
                    size = 30,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
                restingIndicator = {
                    enabled = true,
                    atlasTexture = "plunderstorm-nameplates-icon-2",
                    size = 36,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
            },
        },
        target = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "UIParent",
            relativePoint = "BOTTOM",
            offsetX = 178,
            offsetY = 163,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    frameName = "zfTargetHealth",
                    anchor = "TOP",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "TOP",
                    texture = "smooth",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "zfTargetFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                    },
                    {
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "zfTargetFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                    },
                },
                power = {
                    enabled = true,
                    frameName = "zfTargetPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                castbar = {
                    enabled = true,
                    frameName = "zfTargetCastbar",
                    anchor = "TOP",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "BOTTOM",
                    height = 20,
                    offsetX = 0,
                    offsetY = 0,
                    texture = "smooth",
                    showSpellName = true,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "RIGHT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 2,
                    borderColor = "000000FF",
                },
                auraFilters = {
                    {
                        name = "StaticTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        excludeSubFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "zfStaticTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = 100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActiveTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "zfActiveTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "zfStaticTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActiveTargetDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "zfActiveTargetDebuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "zfActiveTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "FF0000FF",
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    texture = "Diagonal",
                },
            },
        },
        targetTarget = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfTargetTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfTargetFrame",
            relativePoint = "TOPRIGHT",
            offsetX = 10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfTargetTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        focus = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfFocusFrame",
            anchor = "TOPRIGHT",
            relativeTo = "zfPlayerFrame",
            relativePoint = "TOPLEFT",
            offsetX = -10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfFocusFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        focusTarget = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfFocusTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfFocusFrame",
            relativePoint = "BOTTOMLEFT",
            offsetX = 0,
            offsetY = 0,
            width = 75,
            height = 20,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfFocusTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        pet = {
            enabled = true,
            hideBlizzard = true,
            frameName = "zfPetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfPlayerFrame",
            relativePoint = "BOTTOMLEFT",
            offsetX = 0,
            offsetY = -15,
            width = 93,
            height = 29,
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "CENTER",
                        relativeTo = "zfPetFrame",
                        relativePoint = "CENTER",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        party = {
            enabled = true,
            hideBlizzard = true,

            frameName = "zfPartyContainer",
            anchor = "TOPRIGHT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -350,
            offsetY = 150,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 5,
            perRow = 1,
            spacingX = 0,
            spacingY = -1,
            growthX = "RIGHT",
            growthY = "DOWN",

            unitWidth = 150,
            unitHeight = 60,
            unitBackgroundColor = "00000088",
            unitBorderWidth = 2,
            unitBorderColor = "000000FF",
            highlightSelected = true,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 14,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                    {
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[spec]",
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -5,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = true,
                    frameBorderWidth = 0,
                    iconSize = 28,
                    iconBorderWidth = 0,
                    iconBorderColor = "00000000",
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMLEFT",
                    offsetX = 3,
                    offsetY = 3,
                },
                dispelHighlight = {
                    enabled = false,
                    borderWidth = 4,
                },
                trinket = {
                    enabled = true,
                    frameBorderWidth = 2,
                    iconSize = 36,
                    iconBorderWidth = 1,
                    iconBorderColor = "000000FF",
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -6,
                    offsetY = 0,
                    showSwipe = true,
                    showCooldownNumbers = true,
                    cooldownDesaturate = true,
                    cooldownAlpha = 0.5,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    width = 124,
                    height = 18,
                    offsetX = 23,
                    offsetY = 2,
                    texture = "smooth",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 2,
                    textAlignment = "LEFT",
                    showIcon = false,
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                arenaTargets = {
                    enabled = true,
                    anchor = "TOPLEFT",
                    relativePoint = "TOPRIGHT",
                    offsetX = 2,
                    offsetY = 0,
                    mode = "enemy",
                    indicatorWidth = 10,
                    indicatorHeight = 16,
                    spacing = 4,
                    growDirection = "DOWN",
                    maxIndicators = 3,
                    borderWidth = 1,
                    borderColor = "000000FF",
                    containerBackgroundColor = "00000000",
                },
                auraFilters = {
                    {
                        name = "PartyPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = 2,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 5,
                        perRow = 5,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "PartyDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = -4,
                        offsetY = 0,
                        iconSize = 18,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "PartyCrowdControl",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        subFilters = {"CROWD_CONTROL"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 20,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "FF0000",
                        placeholderIcon = "spell_shaman_hex",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "PartyDefensives",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 64,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "00ff98",
                        placeholderIcon = "inv_shield_04",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "PartyImportantBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"IMPORTANT"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 108,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "11aaee",
                        placeholderIcon = "spell_holy_avenginewrath",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                },

            },
        },
        arena = {
            enabled = true,
            hideBlizzard = true,

            frameName = "zfArenaContainer",
            anchor = "TOPLEFT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 350,
            offsetY = 150,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 3,
            perRow = 1,
            spacingX = 0,
            spacingY = -1,
            growthX = "LEFT",
            growthY = "DOWN",

            unitWidth = 150,
            unitHeight = 60,
            unitBackgroundColor = "00000088",
            unitBorderWidth = 2,
            unitBorderColor = "000000FF",
            highlightSelected = true,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 14,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                    {
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[spec]",
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -5,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = true,
                    frameBorderWidth = 0,
                    iconSize = 28,
                    iconBorderWidth = 0,
                    iconBorderColor = "00000000",
                    anchor = "BOTTOMRIGHT",
                    relativePoint = "BOTTOMRIGHT",
                    offsetX = -3,
                    offsetY = 3,
                },
                dispelHighlight = {
                    enabled = false,
                    borderWidth = 4,
                },
                trinket = {
                    enabled = true,
                    frameBorderWidth = 2,
                    iconSize = 36,
                    iconBorderWidth = 1,
                    iconBorderColor = "000000FF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPRIGHT",
                    offsetX = 6,
                    offsetY = 0,
                    showSwipe = true,
                    showCooldownNumbers = true,
                    cooldownDesaturate = true,
                    cooldownAlpha = 0.5,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMRIGHT",
                    relativePoint = "BOTTOMLEFT",
                    width = 124,
                    height = 18,
                    offsetX = -23,
                    offsetY = 2,
                    texture = "smooth",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 2,
                    textAlignment = "LEFT",
                    showIcon = false,
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                arenaTargets = {
                    enabled = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -2,
                    offsetY = 0,
                    mode = "friendly",
                    indicatorWidth = 10,
                    indicatorHeight = 16,
                    spacing = 4,
                    growDirection = "DOWN",
                    maxIndicators = 3,
                    borderWidth = 1,
                    borderColor = "000000FF",
                    containerBackgroundColor = "00000000",
                },
                auraFilters = {
                    {
                        name = "ArenaPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = 2,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 5,
                        perRow = 5,
                        growthX = "RIGHT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ArenaDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 4,
                        offsetY = 0,
                        iconSize = 18,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "RIGHT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ArenaCrowdControl",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        subFilters = {"CROWD_CONTROL"},
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -20,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "FF0000",
                        placeholderIcon = "spell_shaman_hex",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "ArenaDefensives",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -64,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "00ff98",
                        placeholderIcon = "inv_shield_04",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "ArenaImportantBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"IMPORTANT"},
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -108,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "11aaee",
                        placeholderIcon = "spell_holy_avenginewrath",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                },
                drTracker = {
                    enabled = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -150,
                    offsetY = 0,
                    iconSize = 36,
                    iconBorderWidth = 1,
                    iconBorderColor = "000000FF",
                    spacingX = 2,
                    spacingY = 2,
                    maxIcons = 4,
                    perRow = 4,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                },
            },
        },
        auraFilterDebug = {
            enabled = false,
            friendlyUnits = { "player" },
            hostileUnits = { "target" },
        },
    }
end
