local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

-- English
addon.locale.enEN = {
	-- Modules panel
	modulesTitle = "Modules",
	modulesHeader = "Unit Frame Modules",
	experimentalHeader = "Experimental",
	playerEnabled = "Player",
	playerEnabledTooltip = "Enable or disable the player unit frame.",
	targetEnabled = "Target",
	targetEnabledTooltip = "Enable or disable the target unit frame.",
	targetTargetEnabled = "Target of Target",
	targetTargetEnabledTooltip = "Enable or disable the target of target frame.",
	focusEnabled = "Focus",
	focusEnabledTooltip = "Enable or disable the focus unit frame.",
	focusTargetEnabled = "Focus Target",
	focusTargetEnabledTooltip = "Enable or disable the focus target frame.",
	petEnabled = "Pet",
	petEnabledTooltip = "Enable or disable the pet unit frame.",
	partyEnabled = "Party",
	partyEnabledTooltip = "Enable or disable party frames.",
	arenaEnabled = "Arena",
	arenaEnabledTooltip = "Enable or disable arena frames.",
	raidEnabled = "Raid",
	raidEnabledTooltip = "Enable or disable raid frames.",
	blitzEnabled = "Blitz",
	blitzEnabledTooltip = "Enable or disable blitz frames.",
	battlegroundEnabled = "Battlegrounds",
	battlegroundEnabledTooltip = "Enable or disable battleground frames.",
	epicBattlegroundEnabled = "Epic Battlegrounds",
	epicBattlegroundEnabledTooltip = "Enable or disable epic battleground frames.",
	reloadRequiredLabel = "A UI reload is required after enabling or disabling modules.",
	reloadUI = "Reload UI",

	-- Style panel
	styleTitle = "Style",
	styleHeader = "Style Settings",
	font = "Font",
	fontTooltip = "Font used across all unit frames.",
	healthTexture = "Health Texture",
	healthTextureTooltip = "Statusbar texture for health bars.",
	powerTexture = "Power Texture",
	powerTextureTooltip = "Statusbar texture for power bars.",
	castbarTexture = "Castbar Texture",
	castbarTextureTooltip = "Statusbar texture for cast bars.",
	absorbTexture = "Absorb Texture",
	absorbTextureTooltip = "Statusbar texture for absorb overlays.",
	largeFrameLeftText = "Large Frame Left Text",
	largeFrameLeftTextTooltip = "oUF tag string for the left text on player and target frames.",
	largeFrameRightText = "Large Frame Right Text",
	largeFrameRightTextTooltip = "oUF tag string for the right text on player and target frames.",
	smallFrameText = "Small Frame Text",
	smallFrameTextTooltip = "oUF tag string for the text on smaller frames (focus, target of target, etc.).",
	partyFrameLeftText = "Party Frame Left Text",
	partyFrameLeftTextTooltip = "oUF tag string for the left text on party frames.",
	partyFrameRightText = "Party Frame Right Text",
	partyFrameRightTextTooltip = "oUF tag string for the right text on party frames.",
	arenaFrameLeftText = "Arena Frame Left Text",
	arenaFrameLeftTextTooltip = "oUF tag string for the left text on arena frames.",
	arenaFrameRightText = "Arena Frame Right Text",
	arenaFrameRightTextTooltip = "oUF tag string for the right text on arena frames.",
	apply = "Apply",
	textTagHelp = "Tag Info",
	textTagHelpTooltip = "Show a reference of all available text tags.",
	textTagHelpTitle = "Text Tag Reference",
	textTagHelpURL = "Tag docs:",

	-- Party panel
	partyTitle = "Party",
	partyTrinketHeader = "Trinket",
	partyTrinketEnabled = "Show Trinket",
	partyTrinketEnabledTooltip = "Show the PvP trinket cooldown tracker on party frames.",
	partyArenaTargetsHeader = "Arena Targets",
	partyArenaTargetsEnabled = "Show Arena Targets",
	partyArenaTargetsEnabledTooltip = "Show targeting indicators on party frames.",
	partyCastbarHeader = "Castbar",
	partyCastbarEnabled = "Show Castbar",
	partyCastbarEnabledTooltip = "Show the cast bar on party frames.",
	partyCrowdControlHeader = "CC Debuffs",
	partyCrowdControlEnabled = "Show CC Debuffs",
	partyCrowdControlEnabledTooltip = "Show crowd control debuff icons on party frames.",
	partyCrowdControlGlow = "CC Glow",
	partyCrowdControlGlowTooltip = "Show a glow effect on crowd control aura icons.",
	partyCrowdControlGlowColor = "CC Glow Color",
	partyCrowdControlGlowColorTooltip = "Color of the crowd control glow effect.",
	partyDefensivesHeader = "Defensives",
	partyDefensivesEnabled = "Show Defensives",
	partyDefensivesEnabledTooltip = "Show defensive cooldown icons on party frames.",
	partyDefensivesGlow = "Defensives Glow",
	partyDefensivesGlowTooltip = "Show a glow effect on defensive cooldown aura icons.",
	partyDefensivesGlowColor = "Defensives Glow Color",
	partyDefensivesGlowColorTooltip = "Color of the defensives glow effect.",
	partyImportantBuffsHeader = "Important Buffs",
	partyImportantBuffsEnabled = "Show Important Buffs",
	partyImportantBuffsEnabledTooltip = "Show important buff icons on party frames.",
	partyImportantBuffsGlow = "Important Glow",
	partyImportantBuffsGlowTooltip = "Show a glow effect on important buff aura icons.",
	partyImportantBuffsGlowColor = "Important Glow Color",
	partyImportantBuffsGlowColorTooltip = "Color of the important buffs glow effect.",
	partyDispelHeader = "Dispel",
	partyDispelHighlightEnabled = "Show Dispel Borders",
	partyDispelHighlightEnabledTooltip = "Highlight the unit frame border when a dispellable debuff is active.",
	partyDispelIconEnabled = "Show Dispel Icons",
	partyDispelIconEnabledTooltip = "Show a dispel type icon when a dispellable debuff is active.",
	partyReloadDescription = "Reload the UI to apply changes.",

	-- Arena panel
	arenaTitle = "Arena",
	arenaTrinketHeader = "Trinket",
	arenaTrinketEnabled = "Show Trinket",
	arenaTrinketEnabledTooltip = "Show the PvP trinket cooldown tracker on arena frames.",
	arenaArenaTargetsHeader = "Arena Targets",
	arenaArenaTargetsEnabled = "Show Arena Targets",
	arenaArenaTargetsEnabledTooltip = "Show targeting indicators on arena frames.",
	arenaCastbarHeader = "Castbar",
	arenaCastbarEnabled = "Show Castbar",
	arenaCastbarEnabledTooltip = "Show the cast bar on arena frames.",
	arenaCrowdControlHeader = "CC Debuffs",
	arenaCrowdControlEnabled = "Show CC Debuffs",
	arenaCrowdControlEnabledTooltip = "Show crowd control debuff icons on arena frames.",
	arenaCrowdControlGlow = "CC Glow",
	arenaCrowdControlGlowTooltip = "Show a glow effect on crowd control aura icons.",
	arenaCrowdControlGlowColor = "CC Glow Color",
	arenaCrowdControlGlowColorTooltip = "Color of the crowd control glow effect.",
	arenaDefensivesHeader = "Defensives",
	arenaDefensivesEnabled = "Show Defensives",
	arenaDefensivesEnabledTooltip = "Show defensive cooldown icons on arena frames.",
	arenaDefensivesGlow = "Defensives Glow",
	arenaDefensivesGlowTooltip = "Show a glow effect on defensive cooldown aura icons.",
	arenaDefensivesGlowColor = "Defensives Glow Color",
	arenaDefensivesGlowColorTooltip = "Color of the defensives glow effect.",
	arenaImportantBuffsHeader = "Important Buffs",
	arenaImportantBuffsEnabled = "Show Important Buffs",
	arenaImportantBuffsEnabledTooltip = "Show important buff icons on arena frames.",
	arenaImportantBuffsGlow = "Important Glow",
	arenaImportantBuffsGlowTooltip = "Show a glow effect on important buff aura icons.",
	arenaImportantBuffsGlowColor = "Important Glow Color",
	arenaImportantBuffsGlowColorTooltip = "Color of the important buffs glow effect.",
	arenaDRTrackerHeader = "DR Tracker",
	arenaDRTrackerEnabled = "Show DR Tracker",
	arenaDRTrackerEnabledTooltip = "Show diminishing returns tracker on arena frames.",
	arenaDispelHeader = "Dispel",
	arenaDispelHighlightEnabled = "Show Dispel Borders",
	arenaDispelHighlightEnabledTooltip = "Highlight the unit frame border when a dispellable debuff is active.",
	arenaDispelIconEnabled = "Show Dispel Icons",
	arenaDispelIconEnabledTooltip = "Show a dispel type icon when a dispellable debuff is active.",
	arenaReloadDescription = "Reload the UI to apply changes.",
	enabled = "Enable Frame",
	enabledTooltip = "Enable or disable this frame.",

	-- Edit Mode / Settings panel
	editModeHeader = "Edit Mode",
	editModeDescription = "Type |cffffd100/zf to toggle edit mode at any time.",
	editModeButton = "Edit Mode",
	resetAllButton = "Reset All",
	resetButton = "Reset",
	resetConfirmText = "Reset this frame to default? This will clear all customizations for this frame.",
	resetAllConfirmText = "Reset all ZenFrames settings to default? This will clear all customizations and reload your UI.",
	disableModuleConfirmText = "Re-enable later from the main settings panel.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Settings",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "Full edit mode has been implemented and Custom Config removed. If you need help, reach out to reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Enabled",
	emWidth = "Width",
	emHeight = "Height",
	emSize = "Size",
	emSpacing = "Spacing",
	emBorderSize = "Border Size",
	emBorderColor = "Border Color",
	emBackgroundColor = "Background Color",
	emColor = "Color",
	emFont = "Font",
	emFormat = "Format",
	emShadow = "Shadow",
	emOutline = "Outline",
	emLeftClick = "Left Click",
	emRightClick = "Right Click",
	emHideInArena = "Hide in Arena",
	emShowSwipe = "Show Swipe",
	emShowCooldownNumbers = "Show Cooldown Numbers",
	emShowGlow = "Show Glow",
	emGlowColor = "Glow Color",
	emShowPlaceholder = "Show Placeholder",
	emShowIcon = "Show Icon",
	emShowSpellName = "Show Spell Name",
	emShowCastTime = "Show Cast Time",
	emTextSize = "Text Size",
	emTextAlignment = "Text Alignment",
	emIconPosition = "Icon Position",
	emMode = "Mode",
	emIndicatorWidth = "Indicator Width",
	emIndicatorHeight = "Indicator Height",
	emIndicatorSpacing = "Indicator Spacing",
	emGlobalOptions = "Global Options",
	emHealthTexture = "Health Texture",
	emPowerTexture = "Power Texture",
	emAbsorbTexture = "Absorb Texture",
	emCastbarTexture = "Castbar Texture",
	emDisabledModules = "Disabled Modules",
	emNoDisabledModules = "No disabled modules",
	emReloadUI = "Reload UI",
	emTextTagReference = "Text Tag Reference",

	-- Edit mode dropdown options
	emNone = "None",
	emLeft = "Left",
	emRight = "Right",
	emCenter = "Center",
	emThickOutline = "Thick Outline",
	emMonochrome = "Monochrome",
	emSelectTarget = "Select Target",
	emContextMenu = "Context Menu",
	emSetFocus = "Set Focus",
	emClearFocus = "Clear Focus",
	emInspect = "Inspect",
	emShowFriendlyUnits = "Show Friendly Units",
	emShowEnemyUnits = "Show Enemy Units",



	-- Dialog strings
	DialogOk = "OK",

	-- Edit mode UI strings
	emGlobal = "Global",
	emCancel = "Cancel",
	emEnteringEditMode = "Entering Edit Mode",
	emLeavingEditMode = "Leaving Edit Mode",

	-- Edit mode display names
	emDisplayPlayer = "Player",
	emDisplayTarget = "Target",
	emDisplayTargetOfTarget = "Target of Target",
	emDisplayFocus = "Focus",
	emDisplayFocusTarget = "Focus Target",
	emDisplayPet = "Pet",
	emDisplayParty = "Party",
	emDisplayArena = "Arena",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Text Tag Reference|r\n\n|cffffffffTags are enclosed in square brackets and combined with literal text.|r\n\n|cff00ff98Syntax Examples|r\n|cffffd100  [name]|r |cffaaaaaa-> Full unit name|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Class-colored name|r\n\n|cffffffffOptional prefix/suffix (shown only if the tag returns a value):|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Thrall==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Name Tags|r\n|cffffd100  [name]|r |cffffffffFull name|r\n|cffffd100  [name:short]|r |cffffffffShort name|r\n|cffffd100  [name:medium]|r |cffffffffMedium name|r\n|cffffd100  [name:long]|r |cffffffffLong name|r\n|cffffd100  [name:abbrev]|r |cffffffffAbbreviated name|r\n|cffffd100  [name:trunc(12)]|r |cffffffffTruncated to 12 characters|r\n\n|cff00ff98Health Tags|r\n|cffffd100  [curhp]|r |cffffffffCurrent HP (raw number)|r\n|cffffd100  [maxhp]|r |cffffffffMax HP (raw number)|r\n|cffffd100  [perhp]|r |cffffffffHealth percent (e.g. 85)|r\n|cffffd100  [missinghp]|r |cffffffffMissing HP|r\n|cffffd100  [curhp:short]|r |cffffffffCurrent HP abbreviated (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffMax HP abbreviated (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffHealth percent with % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffMissing HP as -245K|r\n\n|cff00ff98Power Tags|r\n|cffffd100  [curpp]|r |cffffffffCurrent power (raw)|r\n|cffffd100  [maxpp]|r |cffffffffMax power (raw)|r\n|cffffd100  [perpp]|r |cffffffffPower percent|r\n|cffffd100  [curpp:short]|r |cffffffffCurrent power abbreviated|r\n|cffffd100  [maxpp:short]|r |cffffffffMax power abbreviated|r\n|cffffd100  [pp:percent]|r |cffffffffPower percent with %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffCurrent - percent%|r\n|cffffd100  [pp:cur-max]|r |cffffffffCurrent / Max|r\n\n|cff00ff98Info Tags|r\n|cffffd100  [level]|r |cffffffffUnit level|r\n|cffffd100  [smartlevel]|r |cffffffffLevel with elite/boss indicator|r\n|cffffd100  [class]|r |cffffffffClass name|r\n|cffffd100  [smartclass]|r |cffffffffClass (players) or creature type (NPCs)|r\n|cffffd100  [spec]|r |cffffffffSpec abbreviation (e.g. ARMS, RESTO)|r\n|cffffd100  [race]|r |cffffffffRace name|r\n|cffffd100  [creature]|r |cffffffffCreature family or type|r\n|cffffd100  [faction]|r |cffffffffFaction name|r\n|cffffd100  [group]|r |cffffffffRaid group number|r\n\n|cff00ff98Status Tags|r\n|cffffd100  [dead]|r |cffffffffDead or Ghost|r\n|cffffd100  [offline]|r |cffffffffOffline if disconnected|r\n|cffffd100  [status]|r |cffffffffDead / Ghost / Offline / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz if resting|r\n|cffffd100  [pvp]|r |cffffffffPvP if flagged|r\n|cffffd100  [leader]|r |cffffffffL if group leader|r\n|cffffd100  [sex]|r |cffffffffMale / Female|r\n\n|cff00ff98Color Tags|r\n|cffffd100  [raidcolor]|r |cffffffffClass color hex (use before name, \\|r after)|r\n|cffffd100  [powercolor]|r |cffffffffPower type color hex|r\n|cffffd100  [threatcolor]|r |cffffffffThreat level color hex|r\n\n|cff00ff98Classification Tags|r\n|cffffd100  [classification]|r |cffffffffRare / Rare Elite / Elite / Boss|r\n|cffffd100  [shortclassification]|r |cffffffffR / R+ / + / B / -|r\n|cffffd100  [threat]|r |cffffffffAggro / ++ / --|r",

}

-- Spanish
addon.locale.esES = {
	-- Modules panel
	modulesTitle = "Módulos",
	modulesHeader = "Módulos de Marco de Unidad",
	experimentalHeader = "Experimental",
	playerEnabled = "Jugador",
	playerEnabledTooltip = "Activar o desactivar el marco del jugador.",
	targetEnabled = "Objetivo",
	targetEnabledTooltip = "Activar o desactivar el marco del objetivo.",
	targetTargetEnabled = "Objetivo del Objetivo",
	targetTargetEnabledTooltip = "Activar o desactivar el marco del objetivo del objetivo.",
	focusEnabled = "Foco",
	focusEnabledTooltip = "Activar o desactivar el marco de foco.",
	focusTargetEnabled = "Objetivo del Foco",
	focusTargetEnabledTooltip = "Activar o desactivar el marco del objetivo del foco.",
	petEnabled = "Mascota",
	petEnabledTooltip = "Activar o desactivar el marco de la mascota.",
	partyEnabled = "Grupo",
	partyEnabledTooltip = "Activar o desactivar los marcos de grupo.",
	arenaEnabled = "Arena",
	arenaEnabledTooltip = "Activar o desactivar los marcos de arena.",
	reloadRequiredLabel = "Se requiere recargar la interfaz después de activar o desactivar módulos.",
	reloadUI = "Recargar Interfaz",

	-- Style panel
	styleTitle = "Estilo",
	styleHeader = "Configuración de Estilo",
	font = "Fuente",
	fontTooltip = "Fuente utilizada en todos los marcos de unidad.",
	healthTexture = "Textura de Salud",
	healthTextureTooltip = "Textura de barra para las barras de salud.",
	powerTexture = "Textura de Poder",
	powerTextureTooltip = "Textura de barra para las barras de poder.",
	castbarTexture = "Textura de Lanzamiento",
	castbarTextureTooltip = "Textura de barra para las barras de lanzamiento.",
	absorbTexture = "Textura de Absorción",
	absorbTextureTooltip = "Textura de barra para las capas de absorción.",
	largeFrameLeftText = "Texto Izquierdo del Marco Grande",
	largeFrameLeftTextTooltip = "Cadena de etiquetas oUF para el texto izquierdo en los marcos de jugador y objetivo.",
	largeFrameRightText = "Texto Derecho del Marco Grande",
	largeFrameRightTextTooltip = "Cadena de etiquetas oUF para el texto derecho en los marcos de jugador y objetivo.",
	smallFrameText = "Texto del Marco Pequeño",
	smallFrameTextTooltip = "Cadena de etiquetas oUF para el texto en marcos más pequeños (foco, objetivo del objetivo, etc.).",
	partyFrameLeftText = "Texto Izquierdo del Marco de Grupo",
	partyFrameLeftTextTooltip = "Cadena de etiquetas oUF para el texto izquierdo en los marcos de grupo.",
	partyFrameRightText = "Texto Derecho del Marco de Grupo",
	partyFrameRightTextTooltip = "Cadena de etiquetas oUF para el texto derecho en los marcos de grupo.",
	arenaFrameLeftText = "Texto Izquierdo del Marco de Arena",
	arenaFrameLeftTextTooltip = "Cadena de etiquetas oUF para el texto izquierdo en los marcos de arena.",
	arenaFrameRightText = "Texto Derecho del Marco de Arena",
	arenaFrameRightTextTooltip = "Cadena de etiquetas oUF para el texto derecho en los marcos de arena.",
	apply = "Aplicar",
	textTagHelp = "Info de Etiquetas",
	textTagHelpTooltip = "Mostrar una referencia de todas las etiquetas de texto disponibles.",
	textTagHelpTitle = "Referencia de Etiquetas de Texto",
	textTagHelpURL = "Documentación de etiquetas:",

	-- Party panel
	partyTitle = "Grupo",
	partyTrinketHeader = "Abalorio",
	partyTrinketEnabled = "Mostrar Abalorio",
	partyTrinketEnabledTooltip = "Mostrar el rastreador de enfriamiento del abalorio JcJ en los marcos de grupo.",
	partyArenaTargetsHeader = "Objetivos de Arena",
	partyArenaTargetsEnabled = "Mostrar Objetivos de Arena",
	partyArenaTargetsEnabledTooltip = "Mostrar indicadores de objetivo en los marcos de grupo.",
	partyCastbarHeader = "Barra de Lanzamiento",
	partyCastbarEnabled = "Mostrar Barra de Lanzamiento",
	partyCastbarEnabledTooltip = "Mostrar la barra de lanzamiento en los marcos de grupo.",
	partyCrowdControlHeader = "Debuffs de CC",
	partyCrowdControlEnabled = "Mostrar Debuffs de CC",
	partyCrowdControlEnabledTooltip = "Mostrar iconos de debuffs de control de masas en los marcos de grupo.",
	partyCrowdControlGlow = "Brillo de CC",
	partyCrowdControlGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de control de masas.",
	partyCrowdControlGlowColor = "Color del Brillo de CC",
	partyCrowdControlGlowColorTooltip = "Color del efecto de brillo de control de masas.",
	partyDefensivesHeader = "Defensivos",
	partyDefensivesEnabled = "Mostrar Defensivos",
	partyDefensivesEnabledTooltip = "Mostrar iconos de enfriamientos defensivos en los marcos de grupo.",
	partyDefensivesGlow = "Brillo de Defensivos",
	partyDefensivesGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de enfriamientos defensivos.",
	partyDefensivesGlowColor = "Color del Brillo de Defensivos",
	partyDefensivesGlowColorTooltip = "Color del efecto de brillo de defensivos.",
	partyImportantBuffsHeader = "Buffs Importantes",
	partyImportantBuffsEnabled = "Mostrar Buffs Importantes",
	partyImportantBuffsEnabledTooltip = "Mostrar iconos de buffs importantes en los marcos de grupo.",
	partyImportantBuffsGlow = "Brillo de Importantes",
	partyImportantBuffsGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de buffs importantes.",
	partyImportantBuffsGlowColor = "Color del Brillo de Importantes",
	partyImportantBuffsGlowColorTooltip = "Color del efecto de brillo de buffs importantes.",
	partyDispelHeader = "Disipar",
	partyDispelHighlightEnabled = "Mostrar Bordes de Disipar",
	partyDispelHighlightEnabledTooltip = "Resaltar el borde del marco cuando un debuff disipable está activo.",
	partyDispelIconEnabled = "Mostrar Iconos de Disipar",
	partyDispelIconEnabledTooltip = "Mostrar un icono del tipo de disipación cuando un debuff disipable está activo.",
	partyReloadDescription = "Recarga la interfaz para aplicar los cambios.",

	-- Arena panel
	arenaTitle = "Arena",
	arenaTrinketHeader = "Abalorio",
	arenaTrinketEnabled = "Mostrar Abalorio",
	arenaTrinketEnabledTooltip = "Mostrar el rastreador de enfriamiento del abalorio JcJ en los marcos de arena.",
	arenaArenaTargetsHeader = "Objetivos de Arena",
	arenaArenaTargetsEnabled = "Mostrar Objetivos de Arena",
	arenaArenaTargetsEnabledTooltip = "Mostrar indicadores de objetivo en los marcos de arena.",
	arenaCastbarHeader = "Barra de Lanzamiento",
	arenaCastbarEnabled = "Mostrar Barra de Lanzamiento",
	arenaCastbarEnabledTooltip = "Mostrar la barra de lanzamiento en los marcos de arena.",
	arenaCrowdControlHeader = "Debuffs de CC",
	arenaCrowdControlEnabled = "Mostrar Debuffs de CC",
	arenaCrowdControlEnabledTooltip = "Mostrar iconos de debuffs de control de masas en los marcos de arena.",
	arenaCrowdControlGlow = "Brillo de CC",
	arenaCrowdControlGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de control de masas.",
	arenaCrowdControlGlowColor = "Color del Brillo de CC",
	arenaCrowdControlGlowColorTooltip = "Color del efecto de brillo de control de masas.",
	arenaDefensivesHeader = "Defensivos",
	arenaDefensivesEnabled = "Mostrar Defensivos",
	arenaDefensivesEnabledTooltip = "Mostrar iconos de enfriamientos defensivos en los marcos de arena.",
	arenaDefensivesGlow = "Brillo de Defensivos",
	arenaDefensivesGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de enfriamientos defensivos.",
	arenaDefensivesGlowColor = "Color del Brillo de Defensivos",
	arenaDefensivesGlowColorTooltip = "Color del efecto de brillo de defensivos.",
	arenaImportantBuffsHeader = "Buffs Importantes",
	arenaImportantBuffsEnabled = "Mostrar Buffs Importantes",
	arenaImportantBuffsEnabledTooltip = "Mostrar iconos de buffs importantes en los marcos de arena.",
	arenaImportantBuffsGlow = "Brillo de Importantes",
	arenaImportantBuffsGlowTooltip = "Mostrar un efecto de brillo en los iconos de auras de buffs importantes.",
	arenaImportantBuffsGlowColor = "Color del Brillo de Importantes",
	arenaImportantBuffsGlowColorTooltip = "Color del efecto de brillo de buffs importantes.",
	arenaDRTrackerHeader = "Rastreador de RD",
	arenaDRTrackerEnabled = "Mostrar Rastreador de RD",
	arenaDRTrackerEnabledTooltip = "Mostrar el rastreador de rendimientos decrecientes en los marcos de arena.",
	arenaDispelHeader = "Disipar",
	arenaDispelHighlightEnabled = "Mostrar Bordes de Disipar",
	arenaDispelHighlightEnabledTooltip = "Resaltar el borde del marco cuando un debuff disipable está activo.",
	arenaDispelIconEnabled = "Mostrar Iconos de Disipar",
	arenaDispelIconEnabledTooltip = "Mostrar un icono del tipo de disipación cuando un debuff disipable está activo.",
	arenaReloadDescription = "Recarga la interfaz para aplicar los cambios.",
	enabled = "Activar Marco",
	enabledTooltip = "Activar o desactivar este marco.",

	-- Edit Mode / Settings panel
	editModeHeader = "Modo de Edición",
	editModeDescription = "Escribe |cffffd100/zf para alternar el modo de edición en cualquier momento.",
	editModeButton = "Modo de Edición",
	resetAllButton = "Restablecer Todo",
	resetButton = "Restablecer",
	resetConfirmText = "¿Restablecer este marco a los valores predeterminados? Esto eliminará todas las personalizaciones de este marco.",
	resetAllConfirmText = "¿Restablecer todos los ajustes de ZenFrames a los valores predeterminados? Esto eliminará todas las personalizaciones y recargará la interfaz.",
	disableModuleConfirmText = "Esto desactivará este módulo.\n\nPuedes reactivarlo más tarde desde el panel principal de ajustes.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Ajustes",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "El modo de edición completo ha sido implementado y la Configuración Personalizada eliminada. Si necesitas ayuda, contacta en reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Activado",
	emWidth = "Ancho",
	emHeight = "Alto",
	emSize = "Tamaño",
	emSpacing = "Espaciado",
	emBorderSize = "Tamaño del Borde",
	emBorderColor = "Color del Borde",
	emBackgroundColor = "Color de Fondo",
	emColor = "Color",
	emFont = "Fuente",
	emFormat = "Formato",
	emShadow = "Sombra",
	emOutline = "Contorno",
	emLeftClick = "Clic Izquierdo",
	emRightClick = "Clic Derecho",
	emHideInArena = "Ocultar en Arena",
	emShowSwipe = "Mostrar Barrido",
	emShowCooldownNumbers = "Mostrar Números de Enfriamiento",
	emShowGlow = "Mostrar Brillo",
	emGlowColor = "Color del Brillo",
	emShowPlaceholder = "Mostrar Marcador",
	emShowIcon = "Mostrar Icono",
	emShowSpellName = "Mostrar Nombre del Hechizo",
	emShowCastTime = "Mostrar Tiempo de Lanzamiento",
	emTextSize = "Tamaño del Texto",
	emTextAlignment = "Alineación del Texto",
	emIconPosition = "Posición del Icono",
	emMode = "Modo",
	emIndicatorWidth = "Ancho del Indicador",
	emIndicatorHeight = "Alto del Indicador",
	emIndicatorSpacing = "Espaciado del Indicador",
	emGlobalOptions = "Opciones Globales",
	emHealthTexture = "Textura de Salud",
	emPowerTexture = "Textura de Poder",
	emAbsorbTexture = "Textura de Absorción",
	emCastbarTexture = "Textura de Lanzamiento",
	emDisabledModules = "Módulos Desactivados",
	emNoDisabledModules = "Sin módulos desactivados",
	emReloadUI = "Recargar Interfaz",
	emTextTagReference = "Referencia de Etiquetas de Texto",

	-- Edit mode dropdown options
	emNone = "Ninguno",
	emLeft = "Izquierda",
	emRight = "Derecha",
	emCenter = "Centro",
	emThickOutline = "Contorno Grueso",
	emMonochrome = "Monocromático",
	emSelectTarget = "Seleccionar Objetivo",
	emContextMenu = "Menú Contextual",
	emSetFocus = "Establecer Foco",
	emClearFocus = "Limpiar Foco",
	emInspect = "Inspeccionar",
	emShowFriendlyUnits = "Mostrar Unidades Aliadas",
	emShowEnemyUnits = "Mostrar Unidades Enemigas",

	-- Dialog strings
	DialogOk = "Aceptar",

	-- Edit mode UI strings
	emGlobal = "Global",
	emCancel = "Cancelar",
	emEnteringEditMode = "Entrando al Modo de Edición",
	emLeavingEditMode = "Saliendo del Modo de Edición",

	-- Edit mode display names
	emDisplayPlayer = "Jugador",
	emDisplayTarget = "Objetivo",
	emDisplayTargetOfTarget = "Objetivo del Objetivo",
	emDisplayFocus = "Foco",
	emDisplayFocusTarget = "Objetivo del Foco",
	emDisplayPet = "Mascota",
	emDisplayParty = "Grupo",
	emDisplayArena = "Arena",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Referencia de Etiquetas de Texto|r\n\n|cffffffffLas etiquetas se encierran entre corchetes y se combinan con texto literal.|r\n\n|cff00ff98Ejemplos de Sintaxis|r\n|cffffd100  [name]|r |cffaaaaaa-> Nombre completo de la unidad|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Nombre con color de clase|r\n\n|cffffffffPrefijo/sufijo opcional (se muestra solo si la etiqueta devuelve un valor):|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Thrall==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Etiquetas de Nombre|r\n|cffffd100  [name]|r |cffffffffNombre completo|r\n|cffffd100  [name:short]|r |cffffffffNombre corto|r\n|cffffd100  [name:medium]|r |cffffffffNombre medio|r\n|cffffd100  [name:long]|r |cffffffffNombre largo|r\n|cffffd100  [name:abbrev]|r |cffffffffNombre abreviado|r\n|cffffd100  [name:trunc(12)]|r |cffffffffTruncado a 12 caracteres|r\n\n|cff00ff98Etiquetas de Salud|r\n|cffffd100  [curhp]|r |cffffffffSalud actual (número bruto)|r\n|cffffd100  [maxhp]|r |cffffffffSalud máxima (número bruto)|r\n|cffffd100  [perhp]|r |cffffffffPorcentaje de salud (ej. 85)|r\n|cffffd100  [missinghp]|r |cffffffffSalud faltante|r\n|cffffd100  [curhp:short]|r |cffffffffSalud actual abreviada (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffSalud máxima abreviada (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffPorcentaje de salud con % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffSalud faltante como -245K|r\n\n|cff00ff98Etiquetas de Poder|r\n|cffffd100  [curpp]|r |cffffffffPoder actual (bruto)|r\n|cffffd100  [maxpp]|r |cffffffffPoder máximo (bruto)|r\n|cffffd100  [perpp]|r |cffffffffPorcentaje de poder|r\n|cffffd100  [curpp:short]|r |cffffffffPoder actual abreviado|r\n|cffffd100  [maxpp:short]|r |cffffffffPoder máximo abreviado|r\n|cffffd100  [pp:percent]|r |cffffffffPorcentaje de poder con %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffActual - porcentaje%|r\n|cffffd100  [pp:cur-max]|r |cffffffffActual / Máximo|r\n\n|cff00ff98Etiquetas de Información|r\n|cffffd100  [level]|r |cffffffffNivel de la unidad|r\n|cffffd100  [smartlevel]|r |cffffffffNivel con indicador élite/jefe|r\n|cffffd100  [class]|r |cffffffffNombre de clase|r\n|cffffd100  [smartclass]|r |cffffffffClase (jugadores) o tipo de criatura (PNJs)|r\n|cffffd100  [spec]|r |cffffffffAbreviación de especialización (ej. ARMAS, RESTO)|r\n|cffffd100  [race]|r |cffffffffNombre de raza|r\n|cffffd100  [creature]|r |cffffffffFamilia o tipo de criatura|r\n|cffffd100  [faction]|r |cffffffffNombre de facción|r\n|cffffd100  [group]|r |cffffffffNúmero de grupo de banda|r\n\n|cff00ff98Etiquetas de Estado|r\n|cffffd100  [dead]|r |cffffffffMuerto o Fantasma|r\n|cffffd100  [offline]|r |cffffffffDesconectado si no está en línea|r\n|cffffd100  [status]|r |cffffffffMuerto / Fantasma / Desconectado / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz si descansando|r\n|cffffd100  [pvp]|r |cffffffffJcJ si activado|r\n|cffffd100  [leader]|r |cffffffffL si líder de grupo|r\n|cffffd100  [sex]|r |cffffffffMasculino / Femenino|r\n\n|cff00ff98Etiquetas de Color|r\n|cffffd100  [raidcolor]|r |cffffffffHex de color de clase (usar antes del nombre, \\|r después)|r\n|cffffd100  [powercolor]|r |cffffffffHex de color del tipo de poder|r\n|cffffd100  [threatcolor]|r |cffffffffHex de color del nivel de amenaza|r\n\n|cff00ff98Etiquetas de Clasificación|r\n|cffffd100  [classification]|r |cffffffffRaro / Raro Élite / Élite / Jefe|r\n|cffffd100  [shortclassification]|r |cffffffffR / R+ / + / J / -|r\n|cffffd100  [threat]|r |cffffffffAggro / ++ / --|r",
}
addon.locale.esMX = addon.locale.esES

-- Brazilian Portuguese
addon.locale.ptBR = {
	-- Modules panel
	modulesTitle = "Módulos",
	modulesHeader = "Módulos de Quadro de Unidade",
	experimentalHeader = "Experimental",
	playerEnabled = "Jogador",
	playerEnabledTooltip = "Ativar ou desativar o quadro do jogador.",
	targetEnabled = "Alvo",
	targetEnabledTooltip = "Ativar ou desativar o quadro do alvo.",
	targetTargetEnabled = "Alvo do Alvo",
	targetTargetEnabledTooltip = "Ativar ou desativar o quadro do alvo do alvo.",
	focusEnabled = "Foco",
	focusEnabledTooltip = "Ativar ou desativar o quadro de foco.",
	focusTargetEnabled = "Alvo do Foco",
	focusTargetEnabledTooltip = "Ativar ou desativar o quadro do alvo do foco.",
	petEnabled = "Mascote",
	petEnabledTooltip = "Ativar ou desativar o quadro do mascote.",
	partyEnabled = "Grupo",
	partyEnabledTooltip = "Ativar ou desativar os quadros de grupo.",
	arenaEnabled = "Arena",
	arenaEnabledTooltip = "Ativar ou desativar os quadros de arena.",
	reloadRequiredLabel = "É necessário recarregar a interface após ativar ou desativar módulos.",
	reloadUI = "Recarregar Interface",

	-- Style panel
	styleTitle = "Estilo",
	styleHeader = "Configurações de Estilo",
	font = "Fonte",
	fontTooltip = "Fonte utilizada em todos os quadros de unidade.",
	healthTexture = "Textura de Vida",
	healthTextureTooltip = "Textura da barra para as barras de vida.",
	powerTexture = "Textura de Poder",
	powerTextureTooltip = "Textura da barra para as barras de poder.",
	castbarTexture = "Textura de Lançamento",
	castbarTextureTooltip = "Textura da barra para as barras de lançamento.",
	absorbTexture = "Textura de Absorção",
	absorbTextureTooltip = "Textura da barra para as camadas de absorção.",
	largeFrameLeftText = "Texto Esquerdo do Quadro Grande",
	largeFrameLeftTextTooltip = "String de tags oUF para o texto esquerdo nos quadros de jogador e alvo.",
	largeFrameRightText = "Texto Direito do Quadro Grande",
	largeFrameRightTextTooltip = "String de tags oUF para o texto direito nos quadros de jogador e alvo.",
	smallFrameText = "Texto do Quadro Pequeno",
	smallFrameTextTooltip = "String de tags oUF para o texto em quadros menores (foco, alvo do alvo, etc.).",
	partyFrameLeftText = "Texto Esquerdo do Quadro de Grupo",
	partyFrameLeftTextTooltip = "String de tags oUF para o texto esquerdo nos quadros de grupo.",
	partyFrameRightText = "Texto Direito do Quadro de Grupo",
	partyFrameRightTextTooltip = "String de tags oUF para o texto direito nos quadros de grupo.",
	arenaFrameLeftText = "Texto Esquerdo do Quadro de Arena",
	arenaFrameLeftTextTooltip = "String de tags oUF para o texto esquerdo nos quadros de arena.",
	arenaFrameRightText = "Texto Direito do Quadro de Arena",
	arenaFrameRightTextTooltip = "String de tags oUF para o texto direito nos quadros de arena.",
	apply = "Aplicar",
	textTagHelp = "Info de Tags",
	textTagHelpTooltip = "Mostrar uma referência de todas as tags de texto disponíveis.",
	textTagHelpTitle = "Referência de Tags de Texto",
	textTagHelpURL = "Documentação de tags:",

	-- Party panel
	partyTitle = "Grupo",
	partyTrinketHeader = "Berloque",
	partyTrinketEnabled = "Mostrar Berloque",
	partyTrinketEnabledTooltip = "Mostrar o rastreador de recarga do berloque JxJ nos quadros de grupo.",
	partyArenaTargetsHeader = "Alvos de Arena",
	partyArenaTargetsEnabled = "Mostrar Alvos de Arena",
	partyArenaTargetsEnabledTooltip = "Mostrar indicadores de alvo nos quadros de grupo.",
	partyCastbarHeader = "Barra de Lançamento",
	partyCastbarEnabled = "Mostrar Barra de Lançamento",
	partyCastbarEnabledTooltip = "Mostrar a barra de lançamento nos quadros de grupo.",
	partyCrowdControlHeader = "Debuffs de CC",
	partyCrowdControlEnabled = "Mostrar Debuffs de CC",
	partyCrowdControlEnabledTooltip = "Mostrar ícones de debuffs de controle de multidão nos quadros de grupo.",
	partyCrowdControlGlow = "Brilho de CC",
	partyCrowdControlGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de controle de multidão.",
	partyCrowdControlGlowColor = "Cor do Brilho de CC",
	partyCrowdControlGlowColorTooltip = "Cor do efeito de brilho de controle de multidão.",
	partyDefensivesHeader = "Defensivos",
	partyDefensivesEnabled = "Mostrar Defensivos",
	partyDefensivesEnabledTooltip = "Mostrar ícones de recargas defensivas nos quadros de grupo.",
	partyDefensivesGlow = "Brilho de Defensivos",
	partyDefensivesGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de recargas defensivas.",
	partyDefensivesGlowColor = "Cor do Brilho de Defensivos",
	partyDefensivesGlowColorTooltip = "Cor do efeito de brilho de defensivos.",
	partyImportantBuffsHeader = "Buffs Importantes",
	partyImportantBuffsEnabled = "Mostrar Buffs Importantes",
	partyImportantBuffsEnabledTooltip = "Mostrar ícones de buffs importantes nos quadros de grupo.",
	partyImportantBuffsGlow = "Brilho de Importantes",
	partyImportantBuffsGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de buffs importantes.",
	partyImportantBuffsGlowColor = "Cor do Brilho de Importantes",
	partyImportantBuffsGlowColorTooltip = "Cor do efeito de brilho de buffs importantes.",
	partyDispelHeader = "Dissipar",
	partyDispelHighlightEnabled = "Mostrar Bordas de Dissipar",
	partyDispelHighlightEnabledTooltip = "Destacar a borda do quadro quando um debuff dissipável está ativo.",
	partyDispelIconEnabled = "Mostrar Ícones de Dissipar",
	partyDispelIconEnabledTooltip = "Mostrar um ícone do tipo de dissipação quando um debuff dissipável está ativo.",
	partyReloadDescription = "Recarregue a interface para aplicar as alterações.",

	-- Arena panel
	arenaTitle = "Arena",
	arenaTrinketHeader = "Berloque",
	arenaTrinketEnabled = "Mostrar Berloque",
	arenaTrinketEnabledTooltip = "Mostrar o rastreador de recarga do berloque JxJ nos quadros de arena.",
	arenaArenaTargetsHeader = "Alvos de Arena",
	arenaArenaTargetsEnabled = "Mostrar Alvos de Arena",
	arenaArenaTargetsEnabledTooltip = "Mostrar indicadores de alvo nos quadros de arena.",
	arenaCastbarHeader = "Barra de Lançamento",
	arenaCastbarEnabled = "Mostrar Barra de Lançamento",
	arenaCastbarEnabledTooltip = "Mostrar a barra de lançamento nos quadros de arena.",
	arenaCrowdControlHeader = "Debuffs de CC",
	arenaCrowdControlEnabled = "Mostrar Debuffs de CC",
	arenaCrowdControlEnabledTooltip = "Mostrar ícones de debuffs de controle de multidão nos quadros de arena.",
	arenaCrowdControlGlow = "Brilho de CC",
	arenaCrowdControlGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de controle de multidão.",
	arenaCrowdControlGlowColor = "Cor do Brilho de CC",
	arenaCrowdControlGlowColorTooltip = "Cor do efeito de brilho de controle de multidão.",
	arenaDefensivesHeader = "Defensivos",
	arenaDefensivesEnabled = "Mostrar Defensivos",
	arenaDefensivesEnabledTooltip = "Mostrar ícones de recargas defensivas nos quadros de arena.",
	arenaDefensivesGlow = "Brilho de Defensivos",
	arenaDefensivesGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de recargas defensivas.",
	arenaDefensivesGlowColor = "Cor do Brilho de Defensivos",
	arenaDefensivesGlowColorTooltip = "Cor do efeito de brilho de defensivos.",
	arenaImportantBuffsHeader = "Buffs Importantes",
	arenaImportantBuffsEnabled = "Mostrar Buffs Importantes",
	arenaImportantBuffsEnabledTooltip = "Mostrar ícones de buffs importantes nos quadros de arena.",
	arenaImportantBuffsGlow = "Brilho de Importantes",
	arenaImportantBuffsGlowTooltip = "Mostrar um efeito de brilho nos ícones de auras de buffs importantes.",
	arenaImportantBuffsGlowColor = "Cor do Brilho de Importantes",
	arenaImportantBuffsGlowColorTooltip = "Cor do efeito de brilho de buffs importantes.",
	arenaDRTrackerHeader = "Rastreador de RD",
	arenaDRTrackerEnabled = "Mostrar Rastreador de RD",
	arenaDRTrackerEnabledTooltip = "Mostrar o rastreador de retornos decrescentes nos quadros de arena.",
	arenaDispelHeader = "Dissipar",
	arenaDispelHighlightEnabled = "Mostrar Bordas de Dissipar",
	arenaDispelHighlightEnabledTooltip = "Destacar a borda do quadro quando um debuff dissipável está ativo.",
	arenaDispelIconEnabled = "Mostrar Ícones de Dissipar",
	arenaDispelIconEnabledTooltip = "Mostrar um ícone do tipo de dissipação quando um debuff dissipável está ativo.",
	arenaReloadDescription = "Recarregue a interface para aplicar as alterações.",
	enabled = "Ativar Quadro",
	enabledTooltip = "Ativar ou desativar este quadro.",

	-- Edit Mode / Settings panel
	editModeHeader = "Modo de Edição",
	editModeDescription = "Digite |cffffd100/zf para alternar o modo de edição a qualquer momento.",
	editModeButton = "Modo de Edição",
	resetAllButton = "Redefinir Tudo",
	resetButton = "Redefinir",
	resetConfirmText = "Redefinir este quadro para o padrão? Isso removerá todas as personalizações deste quadro.",
	resetAllConfirmText = "Redefinir todas as configurações do ZenFrames para o padrão? Isso removerá todas as personalizações e recarregará a interface.",
	disableModuleConfirmText = "Isso desativará este módulo.\n\nVocê pode reativá-lo depois no painel principal de configurações.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Configurações",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "O modo de edição completo foi implementado e a Configuração Personalizada removida. Se precisar de ajuda, entre em contato em reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Ativado",
	emWidth = "Largura",
	emHeight = "Altura",
	emSize = "Tamanho",
	emSpacing = "Espaçamento",
	emBorderSize = "Tamanho da Borda",
	emBorderColor = "Cor da Borda",
	emBackgroundColor = "Cor de Fundo",
	emColor = "Cor",
	emFont = "Fonte",
	emFormat = "Formato",
	emShadow = "Sombra",
	emOutline = "Contorno",
	emLeftClick = "Clique Esquerdo",
	emRightClick = "Clique Direito",
	emHideInArena = "Ocultar na Arena",
	emShowSwipe = "Mostrar Varredura",
	emShowCooldownNumbers = "Mostrar Números de Recarga",
	emShowGlow = "Mostrar Brilho",
	emGlowColor = "Cor do Brilho",
	emShowPlaceholder = "Mostrar Espaço Reservado",
	emShowIcon = "Mostrar Ícone",
	emShowSpellName = "Mostrar Nome do Feitiço",
	emShowCastTime = "Mostrar Tempo de Lançamento",
	emTextSize = "Tamanho do Texto",
	emTextAlignment = "Alinhamento do Texto",
	emIconPosition = "Posição do Ícone",
	emMode = "Modo",
	emIndicatorWidth = "Largura do Indicador",
	emIndicatorHeight = "Altura do Indicador",
	emIndicatorSpacing = "Espaçamento do Indicador",
	emGlobalOptions = "Opções Globais",
	emHealthTexture = "Textura de Vida",
	emPowerTexture = "Textura de Poder",
	emAbsorbTexture = "Textura de Absorção",
	emCastbarTexture = "Textura de Lançamento",
	emDisabledModules = "Módulos Desativados",
	emNoDisabledModules = "Sem módulos desativados",
	emReloadUI = "Recarregar Interface",
	emTextTagReference = "Referência de Tags de Texto",

	-- Edit mode dropdown options
	emNone = "Nenhum",
	emLeft = "Esquerda",
	emRight = "Direita",
	emCenter = "Centro",
	emThickOutline = "Contorno Grosso",
	emMonochrome = "Monocromático",
	emSelectTarget = "Selecionar Alvo",
	emContextMenu = "Menu de Contexto",
	emSetFocus = "Definir Foco",
	emClearFocus = "Limpar Foco",
	emInspect = "Inspecionar",
	emShowFriendlyUnits = "Mostrar Unidades Aliadas",
	emShowEnemyUnits = "Mostrar Unidades Inimigas",

	-- Dialog strings
	DialogOk = "OK",

	-- Edit mode UI strings
	emGlobal = "Global",
	emCancel = "Cancelar",
	emEnteringEditMode = "Entrando no Modo de Edição",
	emLeavingEditMode = "Saindo do Modo de Edição",

	-- Edit mode display names
	emDisplayPlayer = "Jogador",
	emDisplayTarget = "Alvo",
	emDisplayTargetOfTarget = "Alvo do Alvo",
	emDisplayFocus = "Foco",
	emDisplayFocusTarget = "Alvo do Foco",
	emDisplayPet = "Mascote",
	emDisplayParty = "Grupo",
	emDisplayArena = "Arena",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Referência de Tags de Texto|r\n\n|cffffffffAs tags são colocadas entre colchetes e combinadas com texto literal.|r\n\n|cff00ff98Exemplos de Sintaxe|r\n|cffffd100  [name]|r |cffaaaaaa-> Nome completo da unidade|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Nome com cor de classe|r\n\n|cffffffffPrefixo/sufixo opcional (mostrado apenas se a tag retornar um valor):|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Thrall==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Tags de Nome|r\n|cffffd100  [name]|r |cffffffffNome completo|r\n|cffffd100  [name:short]|r |cffffffffNome curto|r\n|cffffd100  [name:medium]|r |cffffffffNome médio|r\n|cffffd100  [name:long]|r |cffffffffNome longo|r\n|cffffd100  [name:abbrev]|r |cffffffffNome abreviado|r\n|cffffd100  [name:trunc(12)]|r |cffffffffTruncado para 12 caracteres|r\n\n|cff00ff98Tags de Vida|r\n|cffffd100  [curhp]|r |cffffffffVida atual (número bruto)|r\n|cffffd100  [maxhp]|r |cffffffffVida máxima (número bruto)|r\n|cffffd100  [perhp]|r |cffffffffPercentual de vida (ex. 85)|r\n|cffffd100  [missinghp]|r |cffffffffVida faltando|r\n|cffffd100  [curhp:short]|r |cffffffffVida atual abreviada (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffVida máxima abreviada (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffPercentual de vida com % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffVida faltando como -245K|r\n\n|cff00ff98Tags de Poder|r\n|cffffd100  [curpp]|r |cffffffffPoder atual (bruto)|r\n|cffffd100  [maxpp]|r |cffffffffPoder máximo (bruto)|r\n|cffffd100  [perpp]|r |cffffffffPercentual de poder|r\n|cffffd100  [curpp:short]|r |cffffffffPoder atual abreviado|r\n|cffffd100  [maxpp:short]|r |cffffffffPoder máximo abreviado|r\n|cffffd100  [pp:percent]|r |cffffffffPercentual de poder com %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffAtual - percentual%|r\n|cffffd100  [pp:cur-max]|r |cffffffffAtual / Máximo|r\n\n|cff00ff98Tags de Informação|r\n|cffffd100  [level]|r |cffffffffNível da unidade|r\n|cffffd100  [smartlevel]|r |cffffffffNível com indicador elite/chefe|r\n|cffffd100  [class]|r |cffffffffNome da classe|r\n|cffffd100  [smartclass]|r |cffffffffClasse (jogadores) ou tipo de criatura (NPCs)|r\n|cffffd100  [spec]|r |cffffffffAbreviação de especialização (ex. ARMAS, RESTO)|r\n|cffffd100  [race]|r |cffffffffNome da raça|r\n|cffffd100  [creature]|r |cffffffffFamília ou tipo de criatura|r\n|cffffd100  [faction]|r |cffffffffNome da facção|r\n|cffffd100  [group]|r |cffffffffNúmero do grupo de raide|r\n\n|cff00ff98Tags de Status|r\n|cffffd100  [dead]|r |cffffffffMorto ou Fantasma|r\n|cffffd100  [offline]|r |cffffffffOffline se desconectado|r\n|cffffd100  [status]|r |cffffffffMorto / Fantasma / Offline / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz se descansando|r\n|cffffd100  [pvp]|r |cffffffffJxJ se ativado|r\n|cffffd100  [leader]|r |cffffffffL se líder do grupo|r\n|cffffd100  [sex]|r |cffffffffMasculino / Feminino|r\n\n|cff00ff98Tags de Cor|r\n|cffffd100  [raidcolor]|r |cffffffffHex de cor de classe (usar antes do nome, \\|r depois)|r\n|cffffd100  [powercolor]|r |cffffffffHex de cor do tipo de poder|r\n|cffffd100  [threatcolor]|r |cffffffffHex de cor do nível de ameaça|r\n\n|cff00ff98Tags de Classificação|r\n|cffffd100  [classification]|r |cffffffffRaro / Raro Elite / Elite / Chefe|r\n|cffffd100  [shortclassification]|r |cffffffffR / R+ / + / C / -|r\n|cffffd100  [threat]|r |cffffffffAggro / ++ / --|r",
}

-- French
addon.locale.frFR = {
	-- Modules panel
	modulesTitle = "Modules",
	modulesHeader = "Modules de Cadre d'Unité",
	experimentalHeader = "Expérimental",
	playerEnabled = "Joueur",
	playerEnabledTooltip = "Activer ou désactiver le cadre du joueur.",
	targetEnabled = "Cible",
	targetEnabledTooltip = "Activer ou désactiver le cadre de la cible.",
	targetTargetEnabled = "Cible de la Cible",
	targetTargetEnabledTooltip = "Activer ou désactiver le cadre de la cible de la cible.",
	focusEnabled = "Focus",
	focusEnabledTooltip = "Activer ou désactiver le cadre de focus.",
	focusTargetEnabled = "Cible du Focus",
	focusTargetEnabledTooltip = "Activer ou désactiver le cadre de la cible du focus.",
	petEnabled = "Familier",
	petEnabledTooltip = "Activer ou désactiver le cadre du familier.",
	partyEnabled = "Groupe",
	partyEnabledTooltip = "Activer ou désactiver les cadres de groupe.",
	arenaEnabled = "Arène",
	arenaEnabledTooltip = "Activer ou désactiver les cadres d'arène.",
	reloadRequiredLabel = "Un rechargement de l'interface est nécessaire après avoir activé ou désactivé des modules.",
	reloadUI = "Recharger l'Interface",

	-- Style panel
	styleTitle = "Style",
	styleHeader = "Paramètres de Style",
	font = "Police",
	fontTooltip = "Police utilisée sur tous les cadres d'unité.",
	healthTexture = "Texture de Vie",
	healthTextureTooltip = "Texture de barre pour les barres de vie.",
	powerTexture = "Texture de Puissance",
	powerTextureTooltip = "Texture de barre pour les barres de puissance.",
	castbarTexture = "Texture d'Incantation",
	castbarTextureTooltip = "Texture de barre pour les barres d'incantation.",
	absorbTexture = "Texture d'Absorption",
	absorbTextureTooltip = "Texture de barre pour les couches d'absorption.",
	largeFrameLeftText = "Texte Gauche du Grand Cadre",
	largeFrameLeftTextTooltip = "Chaîne de tags oUF pour le texte gauche sur les cadres de joueur et cible.",
	largeFrameRightText = "Texte Droit du Grand Cadre",
	largeFrameRightTextTooltip = "Chaîne de tags oUF pour le texte droit sur les cadres de joueur et cible.",
	smallFrameText = "Texte du Petit Cadre",
	smallFrameTextTooltip = "Chaîne de tags oUF pour le texte sur les cadres plus petits (focus, cible de la cible, etc.).",
	partyFrameLeftText = "Texte Gauche du Cadre de Groupe",
	partyFrameLeftTextTooltip = "Chaîne de tags oUF pour le texte gauche sur les cadres de groupe.",
	partyFrameRightText = "Texte Droit du Cadre de Groupe",
	partyFrameRightTextTooltip = "Chaîne de tags oUF pour le texte droit sur les cadres de groupe.",
	arenaFrameLeftText = "Texte Gauche du Cadre d'Arène",
	arenaFrameLeftTextTooltip = "Chaîne de tags oUF pour le texte gauche sur les cadres d'arène.",
	arenaFrameRightText = "Texte Droit du Cadre d'Arène",
	arenaFrameRightTextTooltip = "Chaîne de tags oUF pour le texte droit sur les cadres d'arène.",
	apply = "Appliquer",
	textTagHelp = "Info des Tags",
	textTagHelpTooltip = "Afficher une référence de tous les tags de texte disponibles.",
	textTagHelpTitle = "Référence des Tags de Texte",
	textTagHelpURL = "Documentation des tags :",

	-- Party panel
	partyTitle = "Groupe",
	partyTrinketHeader = "Bijou",
	partyTrinketEnabled = "Afficher le Bijou",
	partyTrinketEnabledTooltip = "Afficher le suivi de recharge du bijou JcJ sur les cadres de groupe.",
	partyArenaTargetsHeader = "Cibles d'Arène",
	partyArenaTargetsEnabled = "Afficher les Cibles d'Arène",
	partyArenaTargetsEnabledTooltip = "Afficher les indicateurs de ciblage sur les cadres de groupe.",
	partyCastbarHeader = "Barre d'Incantation",
	partyCastbarEnabled = "Afficher la Barre d'Incantation",
	partyCastbarEnabledTooltip = "Afficher la barre d'incantation sur les cadres de groupe.",
	partyCrowdControlHeader = "Débuffs de CC",
	partyCrowdControlEnabled = "Afficher les Débuffs de CC",
	partyCrowdControlEnabledTooltip = "Afficher les icônes de débuffs de contrôle de foule sur les cadres de groupe.",
	partyCrowdControlGlow = "Lueur de CC",
	partyCrowdControlGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de contrôle de foule.",
	partyCrowdControlGlowColor = "Couleur de Lueur de CC",
	partyCrowdControlGlowColorTooltip = "Couleur de l'effet de lueur de contrôle de foule.",
	partyDefensivesHeader = "Défensifs",
	partyDefensivesEnabled = "Afficher les Défensifs",
	partyDefensivesEnabledTooltip = "Afficher les icônes de recharges défensives sur les cadres de groupe.",
	partyDefensivesGlow = "Lueur des Défensifs",
	partyDefensivesGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de recharges défensives.",
	partyDefensivesGlowColor = "Couleur de Lueur des Défensifs",
	partyDefensivesGlowColorTooltip = "Couleur de l'effet de lueur des défensifs.",
	partyImportantBuffsHeader = "Buffs Importants",
	partyImportantBuffsEnabled = "Afficher les Buffs Importants",
	partyImportantBuffsEnabledTooltip = "Afficher les icônes de buffs importants sur les cadres de groupe.",
	partyImportantBuffsGlow = "Lueur des Importants",
	partyImportantBuffsGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de buffs importants.",
	partyImportantBuffsGlowColor = "Couleur de Lueur des Importants",
	partyImportantBuffsGlowColorTooltip = "Couleur de l'effet de lueur des buffs importants.",
	partyDispelHeader = "Dissipation",
	partyDispelHighlightEnabled = "Afficher les Bordures de Dissipation",
	partyDispelHighlightEnabledTooltip = "Surligner la bordure du cadre lorsqu'un débuff dissipable est actif.",
	partyDispelIconEnabled = "Afficher les Icônes de Dissipation",
	partyDispelIconEnabledTooltip = "Afficher une icône du type de dissipation lorsqu'un débuff dissipable est actif.",
	partyReloadDescription = "Rechargez l'interface pour appliquer les modifications.",

	-- Arena panel
	arenaTitle = "Arène",
	arenaTrinketHeader = "Bijou",
	arenaTrinketEnabled = "Afficher le Bijou",
	arenaTrinketEnabledTooltip = "Afficher le suivi de recharge du bijou JcJ sur les cadres d'arène.",
	arenaArenaTargetsHeader = "Cibles d'Arène",
	arenaArenaTargetsEnabled = "Afficher les Cibles d'Arène",
	arenaArenaTargetsEnabledTooltip = "Afficher les indicateurs de ciblage sur les cadres d'arène.",
	arenaCastbarHeader = "Barre d'Incantation",
	arenaCastbarEnabled = "Afficher la Barre d'Incantation",
	arenaCastbarEnabledTooltip = "Afficher la barre d'incantation sur les cadres d'arène.",
	arenaCrowdControlHeader = "Débuffs de CC",
	arenaCrowdControlEnabled = "Afficher les Débuffs de CC",
	arenaCrowdControlEnabledTooltip = "Afficher les icônes de débuffs de contrôle de foule sur les cadres d'arène.",
	arenaCrowdControlGlow = "Lueur de CC",
	arenaCrowdControlGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de contrôle de foule.",
	arenaCrowdControlGlowColor = "Couleur de Lueur de CC",
	arenaCrowdControlGlowColorTooltip = "Couleur de l'effet de lueur de contrôle de foule.",
	arenaDefensivesHeader = "Défensifs",
	arenaDefensivesEnabled = "Afficher les Défensifs",
	arenaDefensivesEnabledTooltip = "Afficher les icônes de recharges défensives sur les cadres d'arène.",
	arenaDefensivesGlow = "Lueur des Défensifs",
	arenaDefensivesGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de recharges défensives.",
	arenaDefensivesGlowColor = "Couleur de Lueur des Défensifs",
	arenaDefensivesGlowColorTooltip = "Couleur de l'effet de lueur des défensifs.",
	arenaImportantBuffsHeader = "Buffs Importants",
	arenaImportantBuffsEnabled = "Afficher les Buffs Importants",
	arenaImportantBuffsEnabledTooltip = "Afficher les icônes de buffs importants sur les cadres d'arène.",
	arenaImportantBuffsGlow = "Lueur des Importants",
	arenaImportantBuffsGlowTooltip = "Afficher un effet de lueur sur les icônes d'auras de buffs importants.",
	arenaImportantBuffsGlowColor = "Couleur de Lueur des Importants",
	arenaImportantBuffsGlowColorTooltip = "Couleur de l'effet de lueur des buffs importants.",
	arenaDRTrackerHeader = "Suivi des RD",
	arenaDRTrackerEnabled = "Afficher le Suivi des RD",
	arenaDRTrackerEnabledTooltip = "Afficher le suivi des rendements décroissants sur les cadres d'arène.",
	arenaDispelHeader = "Dissipation",
	arenaDispelHighlightEnabled = "Afficher les Bordures de Dissipation",
	arenaDispelHighlightEnabledTooltip = "Surligner la bordure du cadre lorsqu'un débuff dissipable est actif.",
	arenaDispelIconEnabled = "Afficher les Icônes de Dissipation",
	arenaDispelIconEnabledTooltip = "Afficher une icône du type de dissipation lorsqu'un débuff dissipable est actif.",
	arenaReloadDescription = "Rechargez l'interface pour appliquer les modifications.",
	enabled = "Activer le Cadre",
	enabledTooltip = "Activer ou désactiver ce cadre.",

	-- Edit Mode / Settings panel
	editModeHeader = "Mode Édition",
	editModeDescription = "Tapez |cffffd100/zf pour basculer le mode édition à tout moment.",
	editModeButton = "Mode Édition",
	resetAllButton = "Tout Réinitialiser",
	resetButton = "Réinitialiser",
	resetConfirmText = "Réinitialiser ce cadre aux valeurs par défaut ? Cela supprimera toutes les personnalisations de ce cadre.",
	resetAllConfirmText = "Réinitialiser tous les paramètres de ZenFrames aux valeurs par défaut ? Cela supprimera toutes les personnalisations et rechargera votre interface.",
	disableModuleConfirmText = "Cela désactivera ce module.\n\nVous pourrez le réactiver plus tard depuis le panneau principal des paramètres.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Paramètres",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "Le mode édition complet a été implémenté et la Configuration Personnalisée supprimée. Si vous avez besoin d'aide, contactez reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Activé",
	emWidth = "Largeur",
	emHeight = "Hauteur",
	emSize = "Taille",
	emSpacing = "Espacement",
	emBorderSize = "Taille de Bordure",
	emBorderColor = "Couleur de Bordure",
	emBackgroundColor = "Couleur de Fond",
	emColor = "Couleur",
	emFont = "Police",
	emFormat = "Format",
	emShadow = "Ombre",
	emOutline = "Contour",
	emLeftClick = "Clic Gauche",
	emRightClick = "Clic Droit",
	emHideInArena = "Masquer en Arène",
	emShowSwipe = "Afficher le Balayage",
	emShowCooldownNumbers = "Afficher les Nombres de Recharge",
	emShowGlow = "Afficher la Lueur",
	emGlowColor = "Couleur de Lueur",
	emShowPlaceholder = "Afficher l'Espace Réservé",
	emShowIcon = "Afficher l'Icône",
	emShowSpellName = "Afficher le Nom du Sort",
	emShowCastTime = "Afficher le Temps d'Incantation",
	emTextSize = "Taille du Texte",
	emTextAlignment = "Alignement du Texte",
	emIconPosition = "Position de l'Icône",
	emMode = "Mode",
	emIndicatorWidth = "Largeur de l'Indicateur",
	emIndicatorHeight = "Hauteur de l'Indicateur",
	emIndicatorSpacing = "Espacement de l'Indicateur",
	emGlobalOptions = "Options Globales",
	emHealthTexture = "Texture de Vie",
	emPowerTexture = "Texture de Puissance",
	emAbsorbTexture = "Texture d'Absorption",
	emCastbarTexture = "Texture d'Incantation",
	emDisabledModules = "Modules Désactivés",
	emNoDisabledModules = "Aucun module désactivé",
	emReloadUI = "Recharger l'Interface",
	emTextTagReference = "Référence des Tags de Texte",

	-- Edit mode dropdown options
	emNone = "Aucun",
	emLeft = "Gauche",
	emRight = "Droite",
	emCenter = "Centre",
	emThickOutline = "Contour Épais",
	emMonochrome = "Monochrome",
	emSelectTarget = "Sélectionner la Cible",
	emContextMenu = "Menu Contextuel",
	emSetFocus = "Définir le Focus",
	emClearFocus = "Effacer le Focus",
	emInspect = "Inspecter",
	emShowFriendlyUnits = "Afficher les Unités Alliées",
	emShowEnemyUnits = "Afficher les Unités Ennemies",

	-- Dialog strings
	DialogOk = "OK",

	-- Edit mode UI strings
	emGlobal = "Global",
	emCancel = "Annuler",
	emEnteringEditMode = "Entrée en Mode Édition",
	emLeavingEditMode = "Sortie du Mode Édition",

	-- Edit mode display names
	emDisplayPlayer = "Joueur",
	emDisplayTarget = "Cible",
	emDisplayTargetOfTarget = "Cible de la Cible",
	emDisplayFocus = "Focus",
	emDisplayFocusTarget = "Cible du Focus",
	emDisplayPet = "Familier",
	emDisplayParty = "Groupe",
	emDisplayArena = "Arène",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Référence des Tags de Texte|r\n\n|cffffffffLes tags sont placés entre crochets et combinés avec du texte littéral.|r\n\n|cff00ff98Exemples de Syntaxe|r\n|cffffd100  [name]|r |cffaaaaaa-> Nom complet de l'unité|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Nom coloré par classe|r\n\n|cffffffffPréfixe/suffixe optionnel (affiché uniquement si le tag retourne une valeur) :|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Thrall==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Tags de Nom|r\n|cffffd100  [name]|r |cffffffffNom complet|r\n|cffffd100  [name:short]|r |cffffffffNom court|r\n|cffffd100  [name:medium]|r |cffffffffNom moyen|r\n|cffffd100  [name:long]|r |cffffffffNom long|r\n|cffffd100  [name:abbrev]|r |cffffffffNom abrégé|r\n|cffffd100  [name:trunc(12)]|r |cffffffffTronqué à 12 caractères|r\n\n|cff00ff98Tags de Vie|r\n|cffffd100  [curhp]|r |cffffffffVie actuelle (nombre brut)|r\n|cffffd100  [maxhp]|r |cffffffffVie maximale (nombre brut)|r\n|cffffd100  [perhp]|r |cffffffffPourcentage de vie (ex. 85)|r\n|cffffd100  [missinghp]|r |cffffffffVie manquante|r\n|cffffd100  [curhp:short]|r |cffffffffVie actuelle abrégée (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffVie maximale abrégée (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffPourcentage de vie avec % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffVie manquante en -245K|r\n\n|cff00ff98Tags de Puissance|r\n|cffffd100  [curpp]|r |cffffffffPuissance actuelle (brut)|r\n|cffffd100  [maxpp]|r |cffffffffPuissance maximale (brut)|r\n|cffffd100  [perpp]|r |cffffffffPourcentage de puissance|r\n|cffffd100  [curpp:short]|r |cffffffffPuissance actuelle abrégée|r\n|cffffd100  [maxpp:short]|r |cffffffffPuissance maximale abrégée|r\n|cffffd100  [pp:percent]|r |cffffffffPourcentage de puissance avec %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffActuel - pourcentage%|r\n|cffffd100  [pp:cur-max]|r |cffffffffActuel / Maximum|r\n\n|cff00ff98Tags d'Information|r\n|cffffd100  [level]|r |cffffffffNiveau de l'unité|r\n|cffffd100  [smartlevel]|r |cffffffffNiveau avec indicateur élite/boss|r\n|cffffd100  [class]|r |cffffffffNom de classe|r\n|cffffd100  [smartclass]|r |cffffffffClasse (joueurs) ou type de créature (PNJ)|r\n|cffffd100  [spec]|r |cffffffffAbréviation de spécialisation (ex. ARMES, RESTO)|r\n|cffffd100  [race]|r |cffffffffNom de race|r\n|cffffd100  [creature]|r |cffffffffFamille ou type de créature|r\n|cffffd100  [faction]|r |cffffffffNom de faction|r\n|cffffd100  [group]|r |cffffffffNuméro de groupe de raid|r\n\n|cff00ff98Tags de Statut|r\n|cffffd100  [dead]|r |cffffffffMort ou Fantôme|r\n|cffffd100  [offline]|r |cffffffffHors ligne si déconnecté|r\n|cffffd100  [status]|r |cffffffffMort / Fantôme / Hors ligne / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz si au repos|r\n|cffffd100  [pvp]|r |cffffffffJcJ si activé|r\n|cffffd100  [leader]|r |cffffffffL si chef de groupe|r\n|cffffd100  [sex]|r |cffffffffMasculin / Féminin|r\n\n|cff00ff98Tags de Couleur|r\n|cffffd100  [raidcolor]|r |cffffffffHex de couleur de classe (utiliser avant le nom, \\|r après)|r\n|cffffd100  [powercolor]|r |cffffffffHex de couleur du type de puissance|r\n|cffffd100  [threatcolor]|r |cffffffffHex de couleur du niveau de menace|r\n\n|cff00ff98Tags de Classification|r\n|cffffd100  [classification]|r |cffffffffRare / Rare Élite / Élite / Boss|r\n|cffffd100  [shortclassification]|r |cffffffffR / R+ / + / B / -|r\n|cffffd100  [threat]|r |cffffffffAggro / ++ / --|r",
}

-- German
addon.locale.deDE = {
	-- Modules panel
	modulesTitle = "Module",
	modulesHeader = "Einheitenfenster-Module",
	experimentalHeader = "Experimentell",
	playerEnabled = "Spieler",
	playerEnabledTooltip = "Das Spieler-Einheitenfenster aktivieren oder deaktivieren.",
	targetEnabled = "Ziel",
	targetEnabledTooltip = "Das Ziel-Einheitenfenster aktivieren oder deaktivieren.",
	targetTargetEnabled = "Ziel des Ziels",
	targetTargetEnabledTooltip = "Das Ziel-des-Ziels-Fenster aktivieren oder deaktivieren.",
	focusEnabled = "Fokus",
	focusEnabledTooltip = "Das Fokus-Einheitenfenster aktivieren oder deaktivieren.",
	focusTargetEnabled = "Fokusziel",
	focusTargetEnabledTooltip = "Das Fokusziel-Fenster aktivieren oder deaktivieren.",
	petEnabled = "Begleiter",
	petEnabledTooltip = "Das Begleiter-Einheitenfenster aktivieren oder deaktivieren.",
	partyEnabled = "Gruppe",
	partyEnabledTooltip = "Gruppenfenster aktivieren oder deaktivieren.",
	arenaEnabled = "Arena",
	arenaEnabledTooltip = "Arenafenster aktivieren oder deaktivieren.",
	reloadRequiredLabel = "Nach dem Aktivieren oder Deaktivieren von Modulen ist ein Neuladen der Oberfläche erforderlich.",
	reloadUI = "Oberfläche neu laden",

	-- Style panel
	styleTitle = "Stil",
	styleHeader = "Stil-Einstellungen",
	font = "Schriftart",
	fontTooltip = "Schriftart für alle Einheitenfenster.",
	healthTexture = "Lebenstextur",
	healthTextureTooltip = "Balkentextur für Lebensbalken.",
	powerTexture = "Energietextur",
	powerTextureTooltip = "Balkentextur für Energiebalken.",
	castbarTexture = "Zauberleistentextur",
	castbarTextureTooltip = "Balkentextur für Zauberleisten.",
	absorbTexture = "Absorptionstextur",
	absorbTextureTooltip = "Balkentextur für Absorptionsüberlagerungen.",
	largeFrameLeftText = "Großes Fenster Linker Text",
	largeFrameLeftTextTooltip = "oUF-Tag-String für den linken Text auf Spieler- und Zielfenstern.",
	largeFrameRightText = "Großes Fenster Rechter Text",
	largeFrameRightTextTooltip = "oUF-Tag-String für den rechten Text auf Spieler- und Zielfenstern.",
	smallFrameText = "Kleines Fenster Text",
	smallFrameTextTooltip = "oUF-Tag-String für den Text auf kleineren Fenstern (Fokus, Ziel des Ziels usw.).",
	partyFrameLeftText = "Gruppenfenster Linker Text",
	partyFrameLeftTextTooltip = "oUF-Tag-String für den linken Text auf Gruppenfenstern.",
	partyFrameRightText = "Gruppenfenster Rechter Text",
	partyFrameRightTextTooltip = "oUF-Tag-String für den rechten Text auf Gruppenfenstern.",
	arenaFrameLeftText = "Arenafenster Linker Text",
	arenaFrameLeftTextTooltip = "oUF-Tag-String für den linken Text auf Arenafenstern.",
	arenaFrameRightText = "Arenafenster Rechter Text",
	arenaFrameRightTextTooltip = "oUF-Tag-String für den rechten Text auf Arenafenstern.",
	apply = "Anwenden",
	textTagHelp = "Tag-Info",
	textTagHelpTooltip = "Eine Referenz aller verfügbaren Text-Tags anzeigen.",
	textTagHelpTitle = "Text-Tag-Referenz",
	textTagHelpURL = "Tag-Dokumentation:",

	-- Party panel
	partyTitle = "Gruppe",
	partyTrinketHeader = "Schmuckstück",
	partyTrinketEnabled = "Schmuckstück anzeigen",
	partyTrinketEnabledTooltip = "Den PvP-Schmuckstück-Abklingzeittracker auf Gruppenfenstern anzeigen.",
	partyArenaTargetsHeader = "Arena-Ziele",
	partyArenaTargetsEnabled = "Arena-Ziele anzeigen",
	partyArenaTargetsEnabledTooltip = "Zielindikatoren auf Gruppenfenstern anzeigen.",
	partyCastbarHeader = "Zauberleiste",
	partyCastbarEnabled = "Zauberleiste anzeigen",
	partyCastbarEnabledTooltip = "Die Zauberleiste auf Gruppenfenstern anzeigen.",
	partyCrowdControlHeader = "CC-Debuffs",
	partyCrowdControlEnabled = "CC-Debuffs anzeigen",
	partyCrowdControlEnabledTooltip = "Massenkontrolle-Debuff-Symbole auf Gruppenfenstern anzeigen.",
	partyCrowdControlGlow = "CC-Leuchten",
	partyCrowdControlGlowTooltip = "Einen Leuchteffekt auf Massenkontrolle-Aurasymboolen anzeigen.",
	partyCrowdControlGlowColor = "CC-Leuchtfarbe",
	partyCrowdControlGlowColorTooltip = "Farbe des Massenkontrolle-Leuchteffekts.",
	partyDefensivesHeader = "Defensivfähigkeiten",
	partyDefensivesEnabled = "Defensivfähigkeiten anzeigen",
	partyDefensivesEnabledTooltip = "Defensiv-Abklingzeitsymbole auf Gruppenfenstern anzeigen.",
	partyDefensivesGlow = "Defensiv-Leuchten",
	partyDefensivesGlowTooltip = "Einen Leuchteffekt auf Defensiv-Abklingzeit-Aurasymboolen anzeigen.",
	partyDefensivesGlowColor = "Defensiv-Leuchtfarbe",
	partyDefensivesGlowColorTooltip = "Farbe des Defensiv-Leuchteffekts.",
	partyImportantBuffsHeader = "Wichtige Buffs",
	partyImportantBuffsEnabled = "Wichtige Buffs anzeigen",
	partyImportantBuffsEnabledTooltip = "Wichtige Buff-Symbole auf Gruppenfenstern anzeigen.",
	partyImportantBuffsGlow = "Wichtig-Leuchten",
	partyImportantBuffsGlowTooltip = "Einen Leuchteffekt auf wichtigen Buff-Aurasymboolen anzeigen.",
	partyImportantBuffsGlowColor = "Wichtig-Leuchtfarbe",
	partyImportantBuffsGlowColorTooltip = "Farbe des Wichtig-Leuchteffekts.",
	partyDispelHeader = "Reinigung",
	partyDispelHighlightEnabled = "Reinigungsränder anzeigen",
	partyDispelHighlightEnabledTooltip = "Den Fensterrand hervorheben, wenn ein reinizbarer Debuff aktiv ist.",
	partyDispelIconEnabled = "Reinigungssymbole anzeigen",
	partyDispelIconEnabledTooltip = "Ein Reinigungstyp-Symbol anzeigen, wenn ein reinizbarer Debuff aktiv ist.",
	partyReloadDescription = "Oberfläche neu laden, um Änderungen anzuwenden.",

	-- Arena panel
	arenaTitle = "Arena",
	arenaTrinketHeader = "Schmuckstück",
	arenaTrinketEnabled = "Schmuckstück anzeigen",
	arenaTrinketEnabledTooltip = "Den PvP-Schmuckstück-Abklingzeittracker auf Arenafenstern anzeigen.",
	arenaArenaTargetsHeader = "Arena-Ziele",
	arenaArenaTargetsEnabled = "Arena-Ziele anzeigen",
	arenaArenaTargetsEnabledTooltip = "Zielindikatoren auf Arenafenstern anzeigen.",
	arenaCastbarHeader = "Zauberleiste",
	arenaCastbarEnabled = "Zauberleiste anzeigen",
	arenaCastbarEnabledTooltip = "Die Zauberleiste auf Arenafenstern anzeigen.",
	arenaCrowdControlHeader = "CC-Debuffs",
	arenaCrowdControlEnabled = "CC-Debuffs anzeigen",
	arenaCrowdControlEnabledTooltip = "Massenkontrolle-Debuff-Symbole auf Arenafenstern anzeigen.",
	arenaCrowdControlGlow = "CC-Leuchten",
	arenaCrowdControlGlowTooltip = "Einen Leuchteffekt auf Massenkontrolle-Aurasymboolen anzeigen.",
	arenaCrowdControlGlowColor = "CC-Leuchtfarbe",
	arenaCrowdControlGlowColorTooltip = "Farbe des Massenkontrolle-Leuchteffekts.",
	arenaDefensivesHeader = "Defensivfähigkeiten",
	arenaDefensivesEnabled = "Defensivfähigkeiten anzeigen",
	arenaDefensivesEnabledTooltip = "Defensiv-Abklingzeitsymbole auf Arenafenstern anzeigen.",
	arenaDefensivesGlow = "Defensiv-Leuchten",
	arenaDefensivesGlowTooltip = "Einen Leuchteffekt auf Defensiv-Abklingzeit-Aurasymboolen anzeigen.",
	arenaDefensivesGlowColor = "Defensiv-Leuchtfarbe",
	arenaDefensivesGlowColorTooltip = "Farbe des Defensiv-Leuchteffekts.",
	arenaImportantBuffsHeader = "Wichtige Buffs",
	arenaImportantBuffsEnabled = "Wichtige Buffs anzeigen",
	arenaImportantBuffsEnabledTooltip = "Wichtige Buff-Symbole auf Arenafenstern anzeigen.",
	arenaImportantBuffsGlow = "Wichtig-Leuchten",
	arenaImportantBuffsGlowTooltip = "Einen Leuchteffekt auf wichtigen Buff-Aurasymboolen anzeigen.",
	arenaImportantBuffsGlowColor = "Wichtig-Leuchtfarbe",
	arenaImportantBuffsGlowColorTooltip = "Farbe des Wichtig-Leuchteffekts.",
	arenaDRTrackerHeader = "DR-Tracker",
	arenaDRTrackerEnabled = "DR-Tracker anzeigen",
	arenaDRTrackerEnabledTooltip = "Den Tracker für abnehmende Erträge auf Arenafenstern anzeigen.",
	arenaDispelHeader = "Reinigung",
	arenaDispelHighlightEnabled = "Reinigungsränder anzeigen",
	arenaDispelHighlightEnabledTooltip = "Den Fensterrand hervorheben, wenn ein reinizbarer Debuff aktiv ist.",
	arenaDispelIconEnabled = "Reinigungssymbole anzeigen",
	arenaDispelIconEnabledTooltip = "Ein Reinigungstyp-Symbol anzeigen, wenn ein reinizbarer Debuff aktiv ist.",
	arenaReloadDescription = "Oberfläche neu laden, um Änderungen anzuwenden.",
	enabled = "Fenster aktivieren",
	enabledTooltip = "Dieses Fenster aktivieren oder deaktivieren.",

	-- Edit Mode / Settings panel
	editModeHeader = "Bearbeitungsmodus",
	editModeDescription = "Gib |cffffd100/zf ein, um den Bearbeitungsmodus jederzeit umzuschalten.",
	editModeButton = "Bearbeitungsmodus",
	resetAllButton = "Alles zurücksetzen",
	resetButton = "Zurücksetzen",
	resetConfirmText = "Dieses Fenster auf Standard zurücksetzen? Dies löscht alle Anpassungen für dieses Fenster.",
	resetAllConfirmText = "Alle ZenFrames-Einstellungen auf Standard zurücksetzen? Dies löscht alle Anpassungen und lädt die Oberfläche neu.",
	disableModuleConfirmText = "Dies wird dieses Modul deaktivieren.\n\nDu kannst es später im Haupteinstellungsfenster wieder aktivieren.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Einstellungen",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "Der vollständige Bearbeitungsmodus wurde implementiert und die benutzerdefinierte Konfiguration entfernt. Bei Fragen wende dich an reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Aktiviert",
	emWidth = "Breite",
	emHeight = "Höhe",
	emSize = "Größe",
	emSpacing = "Abstand",
	emBorderSize = "Randgröße",
	emBorderColor = "Randfarbe",
	emBackgroundColor = "Hintergrundfarbe",
	emColor = "Farbe",
	emFont = "Schriftart",
	emFormat = "Format",
	emShadow = "Schatten",
	emOutline = "Umriss",
	emLeftClick = "Linksklick",
	emRightClick = "Rechtsklick",
	emHideInArena = "In Arena ausblenden",
	emShowSwipe = "Wischeffekt anzeigen",
	emShowCooldownNumbers = "Abklingzeitnummern anzeigen",
	emShowGlow = "Leuchten anzeigen",
	emGlowColor = "Leuchtfarbe",
	emShowPlaceholder = "Platzhalter anzeigen",
	emShowIcon = "Symbol anzeigen",
	emShowSpellName = "Zaubername anzeigen",
	emShowCastTime = "Zauberzeit anzeigen",
	emTextSize = "Textgröße",
	emTextAlignment = "Textausrichtung",
	emIconPosition = "Symbolposition",
	emMode = "Modus",
	emIndicatorWidth = "Indikatorbreite",
	emIndicatorHeight = "Indikatorhöhe",
	emIndicatorSpacing = "Indikatorabstand",
	emGlobalOptions = "Globale Optionen",
	emHealthTexture = "Lebenstextur",
	emPowerTexture = "Energietextur",
	emAbsorbTexture = "Absorptionstextur",
	emCastbarTexture = "Zauberleistentextur",
	emDisabledModules = "Deaktivierte Module",
	emNoDisabledModules = "Keine deaktivierten Module",
	emReloadUI = "Oberfläche neu laden",
	emTextTagReference = "Text-Tag-Referenz",

	-- Edit mode dropdown options
	emNone = "Keiner",
	emLeft = "Links",
	emRight = "Rechts",
	emCenter = "Mitte",
	emThickOutline = "Dicker Umriss",
	emMonochrome = "Monochrom",
	emSelectTarget = "Ziel auswählen",
	emContextMenu = "Kontextmenü",
	emSetFocus = "Fokus setzen",
	emClearFocus = "Fokus löschen",
	emInspect = "Inspizieren",
	emShowFriendlyUnits = "Verbündete Einheiten anzeigen",
	emShowEnemyUnits = "Feindliche Einheiten anzeigen",

	-- Dialog strings
	DialogOk = "OK",

	-- Edit mode UI strings
	emGlobal = "Global",
	emCancel = "Abbrechen",
	emEnteringEditMode = "Bearbeitungsmodus wird gestartet",
	emLeavingEditMode = "Bearbeitungsmodus wird beendet",

	-- Edit mode display names
	emDisplayPlayer = "Spieler",
	emDisplayTarget = "Ziel",
	emDisplayTargetOfTarget = "Ziel des Ziels",
	emDisplayFocus = "Fokus",
	emDisplayFocusTarget = "Fokusziel",
	emDisplayPet = "Begleiter",
	emDisplayParty = "Gruppe",
	emDisplayArena = "Arena",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Text-Tag-Referenz|r\n\n|cffffffffTags werden in eckige Klammern gesetzt und mit Klartext kombiniert.|r\n\n|cff00ff98Syntaxbeispiele|r\n|cffffd100  [name]|r |cffaaaaaa-> Vollständiger Einheitenname|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Klassenfarbiger Name|r\n\n|cffffffffOptionaler Präfix/Suffix (wird nur angezeigt, wenn der Tag einen Wert zurückgibt):|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Thrall==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Namens-Tags|r\n|cffffd100  [name]|r |cffffffffVollständiger Name|r\n|cffffd100  [name:short]|r |cffffffffKurzer Name|r\n|cffffd100  [name:medium]|r |cffffffffMittlerer Name|r\n|cffffd100  [name:long]|r |cffffffffLanger Name|r\n|cffffd100  [name:abbrev]|r |cffffffffAbgekürzter Name|r\n|cffffd100  [name:trunc(12)]|r |cffffffffAuf 12 Zeichen gekürzt|r\n\n|cff00ff98Lebens-Tags|r\n|cffffd100  [curhp]|r |cffffffffAktuelles Leben (Rohzahl)|r\n|cffffd100  [maxhp]|r |cffffffffMaximales Leben (Rohzahl)|r\n|cffffd100  [perhp]|r |cffffffffLebensprozent (z.B. 85)|r\n|cffffd100  [missinghp]|r |cffffffffFehlendes Leben|r\n|cffffd100  [curhp:short]|r |cffffffffAktuelles Leben abgekürzt (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffMaximales Leben abgekürzt (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffLebensprozent mit % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffFehlendes Leben als -245K|r\n\n|cff00ff98Energie-Tags|r\n|cffffd100  [curpp]|r |cffffffffAktuelle Energie (roh)|r\n|cffffd100  [maxpp]|r |cffffffffMaximale Energie (roh)|r\n|cffffd100  [perpp]|r |cffffffffEnergieprozent|r\n|cffffd100  [curpp:short]|r |cffffffffAktuelle Energie abgekürzt|r\n|cffffd100  [maxpp:short]|r |cffffffffMaximale Energie abgekürzt|r\n|cffffd100  [pp:percent]|r |cffffffffEnergieprozent mit %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffAktuell - Prozent%|r\n|cffffd100  [pp:cur-max]|r |cffffffffAktuell / Maximum|r\n\n|cff00ff98Info-Tags|r\n|cffffd100  [level]|r |cffffffffEinheitenstufe|r\n|cffffd100  [smartlevel]|r |cffffffffStufe mit Elite/Boss-Indikator|r\n|cffffd100  [class]|r |cffffffffKlassenname|r\n|cffffd100  [smartclass]|r |cffffffffKlasse (Spieler) oder Kreaturtyp (NPCs)|r\n|cffffd100  [spec]|r |cffffffffSpezialisierungskürzel (z.B. WAFFEN, WIEDERH)|r\n|cffffd100  [race]|r |cffffffffVolksname|r\n|cffffd100  [creature]|r |cffffffffKreaturfamilie oder -typ|r\n|cffffd100  [faction]|r |cffffffffFraktionsname|r\n|cffffd100  [group]|r |cffffffffSchlachtzugsgruppennummer|r\n\n|cff00ff98Status-Tags|r\n|cffffd100  [dead]|r |cffffffffTot oder Geist|r\n|cffffd100  [offline]|r |cffffffffOffline wenn getrennt|r\n|cffffd100  [status]|r |cffffffffTot / Geist / Offline / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz wenn ruhend|r\n|cffffd100  [pvp]|r |cffffffffPvP wenn aktiviert|r\n|cffffd100  [leader]|r |cffffffffL wenn Gruppenleiter|r\n|cffffd100  [sex]|r |cffffffffMännlich / Weiblich|r\n\n|cff00ff98Farb-Tags|r\n|cffffd100  [raidcolor]|r |cffffffffKlassenfarbe-Hex (vor dem Namen verwenden, \\|r danach)|r\n|cffffd100  [powercolor]|r |cffffffffEnergietyp-Farbe-Hex|r\n|cffffd100  [threatcolor]|r |cffffffffBedrohungsstufe-Farbe-Hex|r\n\n|cff00ff98Klassifizierungs-Tags|r\n|cffffd100  [classification]|r |cffffffffSelten / Selten Elite / Elite / Boss|r\n|cffffd100  [shortclassification]|r |cffffffffS / S+ / + / B / -|r\n|cffffd100  [threat]|r |cffffffffAggro / ++ / --|r",
}

-- Russian
addon.locale.ruRU = {
	-- Modules panel
	modulesTitle = "Модули",
	modulesHeader = "Модули окон юнитов",
	experimentalHeader = "Экспериментальные",
	playerEnabled = "Игрок",
	playerEnabledTooltip = "Включить или отключить окно игрока.",
	targetEnabled = "Цель",
	targetEnabledTooltip = "Включить или отключить окно цели.",
	targetTargetEnabled = "Цель цели",
	targetTargetEnabledTooltip = "Включить или отключить окно цели цели.",
	focusEnabled = "Фокус",
	focusEnabledTooltip = "Включить или отключить окно фокуса.",
	focusTargetEnabled = "Цель фокуса",
	focusTargetEnabledTooltip = "Включить или отключить окно цели фокуса.",
	petEnabled = "Питомец",
	petEnabledTooltip = "Включить или отключить окно питомца.",
	partyEnabled = "Группа",
	partyEnabledTooltip = "Включить или отключить окна группы.",
	arenaEnabled = "Арена",
	arenaEnabledTooltip = "Включить или отключить окна арены.",
	reloadRequiredLabel = "После включения или отключения модулей требуется перезагрузка интерфейса.",
	reloadUI = "Перезагрузить интерфейс",

	-- Style panel
	styleTitle = "Стиль",
	styleHeader = "Настройки стиля",
	font = "Шрифт",
	fontTooltip = "Шрифт, используемый для всех окон юнитов.",
	healthTexture = "Текстура здоровья",
	healthTextureTooltip = "Текстура полосы для полос здоровья.",
	powerTexture = "Текстура ресурса",
	powerTextureTooltip = "Текстура полосы для полос ресурса.",
	castbarTexture = "Текстура заклинаний",
	castbarTextureTooltip = "Текстура полосы для полос заклинаний.",
	absorbTexture = "Текстура поглощения",
	absorbTextureTooltip = "Текстура полосы для слоёв поглощения.",
	largeFrameLeftText = "Левый текст большого окна",
	largeFrameLeftTextTooltip = "Строка тегов oUF для левого текста на окнах игрока и цели.",
	largeFrameRightText = "Правый текст большого окна",
	largeFrameRightTextTooltip = "Строка тегов oUF для правого текста на окнах игрока и цели.",
	smallFrameText = "Текст малого окна",
	smallFrameTextTooltip = "Строка тегов oUF для текста на малых окнах (фокус, цель цели и т.д.).",
	partyFrameLeftText = "Левый текст окна группы",
	partyFrameLeftTextTooltip = "Строка тегов oUF для левого текста на окнах группы.",
	partyFrameRightText = "Правый текст окна группы",
	partyFrameRightTextTooltip = "Строка тегов oUF для правого текста на окнах группы.",
	arenaFrameLeftText = "Левый текст окна арены",
	arenaFrameLeftTextTooltip = "Строка тегов oUF для левого текста на окнах арены.",
	arenaFrameRightText = "Правый текст окна арены",
	arenaFrameRightTextTooltip = "Строка тегов oUF для правого текста на окнах арены.",
	apply = "Применить",
	textTagHelp = "Справка по тегам",
	textTagHelpTooltip = "Показать справочник всех доступных текстовых тегов.",
	textTagHelpTitle = "Справочник текстовых тегов",
	textTagHelpURL = "Документация тегов:",

	-- Party panel
	partyTitle = "Группа",
	partyTrinketHeader = "Аксессуар",
	partyTrinketEnabled = "Показать аксессуар",
	partyTrinketEnabledTooltip = "Показать трекер перезарядки PvP-аксессуара на окнах группы.",
	partyArenaTargetsHeader = "Цели арены",
	partyArenaTargetsEnabled = "Показать цели арены",
	partyArenaTargetsEnabledTooltip = "Показать индикаторы целей на окнах группы.",
	partyCastbarHeader = "Полоса заклинаний",
	partyCastbarEnabled = "Показать полосу заклинаний",
	partyCastbarEnabledTooltip = "Показать полосу заклинаний на окнах группы.",
	partyCrowdControlHeader = "Дебаффы контроля",
	partyCrowdControlEnabled = "Показать дебаффы контроля",
	partyCrowdControlEnabledTooltip = "Показать значки дебаффов контроля на окнах группы.",
	partyCrowdControlGlow = "Свечение контроля",
	partyCrowdControlGlowTooltip = "Показать эффект свечения на значках аур контроля.",
	partyCrowdControlGlowColor = "Цвет свечения контроля",
	partyCrowdControlGlowColorTooltip = "Цвет эффекта свечения контроля.",
	partyDefensivesHeader = "Защитные способности",
	partyDefensivesEnabled = "Показать защитные",
	partyDefensivesEnabledTooltip = "Показать значки защитных перезарядок на окнах группы.",
	partyDefensivesGlow = "Свечение защитных",
	partyDefensivesGlowTooltip = "Показать эффект свечения на значках аур защитных перезарядок.",
	partyDefensivesGlowColor = "Цвет свечения защитных",
	partyDefensivesGlowColorTooltip = "Цвет эффекта свечения защитных способностей.",
	partyImportantBuffsHeader = "Важные баффы",
	partyImportantBuffsEnabled = "Показать важные баффы",
	partyImportantBuffsEnabledTooltip = "Показать значки важных баффов на окнах группы.",
	partyImportantBuffsGlow = "Свечение важных",
	partyImportantBuffsGlowTooltip = "Показать эффект свечения на значках аур важных баффов.",
	partyImportantBuffsGlowColor = "Цвет свечения важных",
	partyImportantBuffsGlowColorTooltip = "Цвет эффекта свечения важных баффов.",
	partyDispelHeader = "Рассеивание",
	partyDispelHighlightEnabled = "Показать рамки рассеивания",
	partyDispelHighlightEnabledTooltip = "Подсветить рамку окна юнита при наличии рассеиваемого дебаффа.",
	partyDispelIconEnabled = "Показать значки рассеивания",
	partyDispelIconEnabledTooltip = "Показать значок типа рассеивания при наличии рассеиваемого дебаффа.",
	partyReloadDescription = "Перезагрузите интерфейс для применения изменений.",

	-- Arena panel
	arenaTitle = "Арена",
	arenaTrinketHeader = "Аксессуар",
	arenaTrinketEnabled = "Показать аксессуар",
	arenaTrinketEnabledTooltip = "Показать трекер перезарядки PvP-аксессуара на окнах арены.",
	arenaArenaTargetsHeader = "Цели арены",
	arenaArenaTargetsEnabled = "Показать цели арены",
	arenaArenaTargetsEnabledTooltip = "Показать индикаторы целей на окнах арены.",
	arenaCastbarHeader = "Полоса заклинаний",
	arenaCastbarEnabled = "Показать полосу заклинаний",
	arenaCastbarEnabledTooltip = "Показать полосу заклинаний на окнах арены.",
	arenaCrowdControlHeader = "Дебаффы контроля",
	arenaCrowdControlEnabled = "Показать дебаффы контроля",
	arenaCrowdControlEnabledTooltip = "Показать значки дебаффов контроля на окнах арены.",
	arenaCrowdControlGlow = "Свечение контроля",
	arenaCrowdControlGlowTooltip = "Показать эффект свечения на значках аур контроля.",
	arenaCrowdControlGlowColor = "Цвет свечения контроля",
	arenaCrowdControlGlowColorTooltip = "Цвет эффекта свечения контроля.",
	arenaDefensivesHeader = "Защитные способности",
	arenaDefensivesEnabled = "Показать защитные",
	arenaDefensivesEnabledTooltip = "Показать значки защитных перезарядок на окнах арены.",
	arenaDefensivesGlow = "Свечение защитных",
	arenaDefensivesGlowTooltip = "Показать эффект свечения на значках аур защитных перезарядок.",
	arenaDefensivesGlowColor = "Цвет свечения защитных",
	arenaDefensivesGlowColorTooltip = "Цвет эффекта свечения защитных способностей.",
	arenaImportantBuffsHeader = "Важные баффы",
	arenaImportantBuffsEnabled = "Показать важные баффы",
	arenaImportantBuffsEnabledTooltip = "Показать значки важных баффов на окнах арены.",
	arenaImportantBuffsGlow = "Свечение важных",
	arenaImportantBuffsGlowTooltip = "Показать эффект свечения на значках аур важных баффов.",
	arenaImportantBuffsGlowColor = "Цвет свечения важных",
	arenaImportantBuffsGlowColorTooltip = "Цвет эффекта свечения важных баффов.",
	arenaDRTrackerHeader = "Трекер убыв. отдачи",
	arenaDRTrackerEnabled = "Показать трекер убыв. отдачи",
	arenaDRTrackerEnabledTooltip = "Показать трекер убывающей отдачи на окнах арены.",
	arenaDispelHeader = "Рассеивание",
	arenaDispelHighlightEnabled = "Показать рамки рассеивания",
	arenaDispelHighlightEnabledTooltip = "Подсветить рамку окна юнита при наличии рассеиваемого дебаффа.",
	arenaDispelIconEnabled = "Показать значки рассеивания",
	arenaDispelIconEnabledTooltip = "Показать значок типа рассеивания при наличии рассеиваемого дебаффа.",
	arenaReloadDescription = "Перезагрузите интерфейс для применения изменений.",
	enabled = "Включить окно",
	enabledTooltip = "Включить или отключить это окно.",

	-- Edit Mode / Settings panel
	editModeHeader = "Режим редактирования",
	editModeDescription = "Введите |cffffd100/zf для переключения режима редактирования в любое время.",
	editModeButton = "Режим редактирования",
	resetAllButton = "Сбросить всё",
	resetButton = "Сбросить",
	resetConfirmText = "Сбросить это окно до значений по умолчанию? Все настройки этого окна будут удалены.",
	resetAllConfirmText = "Сбросить все настройки ZenFrames до значений по умолчанию? Все настройки будут удалены, а интерфейс перезагружен.",
	disableModuleConfirmText = "Это отключит данный модуль.\n\nВы сможете включить его позже в главной панели настроек.",
	editModeDialogTitle = "ZenFrames",
	settingsTitle = "Настройки",
	editModeAuthorCredit = "by Rôkk-Wyrmrest Accord",
	customConfigRemoved = "Полный режим редактирования реализован, а пользовательская конфигурация удалена. Если вам нужна помощь, обращайтесь на reddit.com/u/rokk--/.",

	-- Edit mode control labels (shared across dialogs)
	emEnabled = "Включено",
	emWidth = "Ширина",
	emHeight = "Высота",
	emSize = "Размер",
	emSpacing = "Интервал",
	emBorderSize = "Размер рамки",
	emBorderColor = "Цвет рамки",
	emBackgroundColor = "Цвет фона",
	emColor = "Цвет",
	emFont = "Шрифт",
	emFormat = "Формат",
	emShadow = "Тень",
	emOutline = "Контур",
	emLeftClick = "Левый клик",
	emRightClick = "Правый клик",
	emHideInArena = "Скрыть на арене",
	emShowSwipe = "Показать затемнение",
	emShowCooldownNumbers = "Показать числа перезарядки",
	emShowGlow = "Показать свечение",
	emGlowColor = "Цвет свечения",
	emShowPlaceholder = "Показать заполнитель",
	emShowIcon = "Показать значок",
	emShowSpellName = "Показать название заклинания",
	emShowCastTime = "Показать время произнесения",
	emTextSize = "Размер текста",
	emTextAlignment = "Выравнивание текста",
	emIconPosition = "Позиция значка",
	emMode = "Режим",
	emIndicatorWidth = "Ширина индикатора",
	emIndicatorHeight = "Высота индикатора",
	emIndicatorSpacing = "Интервал индикатора",
	emGlobalOptions = "Глобальные настройки",
	emHealthTexture = "Текстура здоровья",
	emPowerTexture = "Текстура ресурса",
	emAbsorbTexture = "Текстура поглощения",
	emCastbarTexture = "Текстура заклинаний",
	emDisabledModules = "Отключённые модули",
	emNoDisabledModules = "Нет отключённых модулей",
	emReloadUI = "Перезагрузить интерфейс",
	emTextTagReference = "Справочник текстовых тегов",

	-- Edit mode dropdown options
	emNone = "Нет",
	emLeft = "Слева",
	emRight = "Справа",
	emCenter = "По центру",
	emThickOutline = "Толстый контур",
	emMonochrome = "Монохромный",
	emSelectTarget = "Выбрать цель",
	emContextMenu = "Контекстное меню",
	emSetFocus = "Установить фокус",
	emClearFocus = "Сбросить фокус",
	emInspect = "Осмотреть",
	emShowFriendlyUnits = "Показать дружественных",
	emShowEnemyUnits = "Показать вражеских",

	-- Dialog strings
	DialogOk = "ОК",

	-- Edit mode UI strings
	emGlobal = "Глобально",
	emCancel = "Отмена",
	emEnteringEditMode = "Вход в режим редактирования",
	emLeavingEditMode = "Выход из режима редактирования",

	-- Edit mode display names
	emDisplayPlayer = "Игрок",
	emDisplayTarget = "Цель",
	emDisplayTargetOfTarget = "Цель цели",
	emDisplayFocus = "Фокус",
	emDisplayFocusTarget = "Цель фокуса",
	emDisplayPet = "Питомец",
	emDisplayParty = "Группа",
	emDisplayArena = "Арена",

	-- Text tag help content
	emTextTagHelpContent = "|cff00ff98Справочник текстовых тегов|r\n\n|cffffffffТеги заключаются в квадратные скобки и комбинируются с обычным текстом.|r\n\n|cff00ff98Примеры синтаксиса|r\n|cffffd100  [name]|r |cffaaaaaa-> Полное имя юнита|r\n|cffffd100  [perhp]%|r |cffaaaaaa-> 85%|r\n|cffffd100  [curhp:short] / [maxhp:short]|r |cffaaaaaa-> 245K / 300K|r\n|cffffd100  [raidcolor][name:medium]\\|r|r |cffaaaaaa-> Имя в цвете класса|r\n\n|cffffffffНеобязательный префикс/суффикс (отображается, только если тег возвращает значение):|r\n|cffffd100  [==$>name<$==]|r |cffaaaaaa-> ==Тралл==|r\n|cffffd100  [perhp<$%]|r |cffaaaaaa-> 85%|r\n\n|cff00ff98Теги имени|r\n|cffffd100  [name]|r |cffffffffПолное имя|r\n|cffffd100  [name:short]|r |cffffffffКороткое имя|r\n|cffffd100  [name:medium]|r |cffffffffСреднее имя|r\n|cffffd100  [name:long]|r |cffffffffДлинное имя|r\n|cffffd100  [name:abbrev]|r |cffffffffСокращённое имя|r\n|cffffd100  [name:trunc(12)]|r |cffffffffОбрезано до 12 символов|r\n\n|cff00ff98Теги здоровья|r\n|cffffd100  [curhp]|r |cffffffffТекущее здоровье (число)|r\n|cffffd100  [maxhp]|r |cffffffffМаксимальное здоровье (число)|r\n|cffffd100  [perhp]|r |cffffffffПроцент здоровья (напр. 85)|r\n|cffffd100  [missinghp]|r |cffffffffНедостающее здоровье|r\n|cffffd100  [curhp:short]|r |cffffffffТекущее здоровье сокращённо (245K)|r\n|cffffd100  [maxhp:short]|r |cffffffffМаксимальное здоровье сокращённо (300K)|r\n|cffffd100  [hp:percent]|r |cffffffffПроцент здоровья с % (85%)|r\n|cffffd100  [hp:cur-percent]|r |cffffffff245K - 85%|r\n|cffffd100  [hp:cur-max]|r |cffffffff245K / 300K|r\n|cffffd100  [hp:deficit]|r |cffffffffНедостающее здоровье как -245K|r\n\n|cff00ff98Теги ресурса|r\n|cffffd100  [curpp]|r |cffffffffТекущий ресурс (число)|r\n|cffffd100  [maxpp]|r |cffffffffМаксимальный ресурс (число)|r\n|cffffd100  [perpp]|r |cffffffffПроцент ресурса|r\n|cffffd100  [curpp:short]|r |cffffffffТекущий ресурс сокращённо|r\n|cffffd100  [maxpp:short]|r |cffffffffМаксимальный ресурс сокращённо|r\n|cffffd100  [pp:percent]|r |cffffffffПроцент ресурса с %|r\n|cffffd100  [pp:cur-percent]|r |cffffffffТекущий - процент%|r\n|cffffd100  [pp:cur-max]|r |cffffffffТекущий / Максимум|r\n\n|cff00ff98Теги информации|r\n|cffffd100  [level]|r |cffffffffУровень юнита|r\n|cffffd100  [smartlevel]|r |cffffffffУровень с индикатором элиты/босса|r\n|cffffd100  [class]|r |cffffffffНазвание класса|r\n|cffffd100  [smartclass]|r |cffffffffКласс (игроки) или тип существа (НИП)|r\n|cffffd100  [spec]|r |cffffffffСокращение специализации (напр. ОРУЖ, ВОССТ)|r\n|cffffd100  [race]|r |cffffffffНазвание расы|r\n|cffffd100  [creature]|r |cffffffffСемейство или тип существа|r\n|cffffd100  [faction]|r |cffffffffНазвание фракции|r\n|cffffd100  [group]|r |cffffffffНомер рейдовой группы|r\n\n|cff00ff98Теги состояния|r\n|cffffd100  [dead]|r |cffffffffМёртв или Призрак|r\n|cffffd100  [offline]|r |cffffffffНе в сети|r\n|cffffd100  [status]|r |cffffffffМёртв / Призрак / Не в сети / zzz|r\n|cffffd100  [resting]|r |cffffffffzzz если отдыхает|r\n|cffffd100  [pvp]|r |cffffffffPvP если включено|r\n|cffffd100  [leader]|r |cffffffffЛ если лидер группы|r\n|cffffd100  [sex]|r |cffffffffМужской / Женский|r\n\n|cff00ff98Теги цвета|r\n|cffffd100  [raidcolor]|r |cffffffffHex цвета класса (перед именем, \\|r после)|r\n|cffffd100  [powercolor]|r |cffffffffHex цвета типа ресурса|r\n|cffffd100  [threatcolor]|r |cffffffffHex цвета уровня угрозы|r\n\n|cff00ff98Теги классификации|r\n|cffffd100  [classification]|r |cffffffffРедкий / Редкий элитный / Элитный / Босс|r\n|cffffd100  [shortclassification]|r |cffffffffР / Р+ / + / Б / -|r\n|cffffd100  [threat]|r |cffffffffАггро / ++ / --|r",
}
