local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Arena()
    return {
        enabled = true,
        hideBlizzard = true,

        frameName = "zfArenaContainer",
        anchor = "LEFT",
        relativeTo = "UIParent",
        relativePoint = "CENTER",
        offsetX = 370,
        offsetY = 63,
        containerBackgroundColor = "00000000",
        containerBorderWidth = 0,
        containerBorderColor = "00000000",

        maxUnits = 3,
        perRow = 1,
        spacingX = 0,
        spacingY = 3,
        growthX = "LEFT",
        growthY = "DOWN",

        unitWidth = 150,
        unitHeight = 60,
        unitBackgroundColor = "00000088",
        borderWidth = "_GLOBAL_",
        borderColor = "_GLOBAL_",
        outOfRangeOpacity = "_GLOBAL_",
        highlightSelected = true,

        leftClick = "select",
        rightClick = "contextMenu",
        hideInArena = false,

        modules = {
            health = {
                enabled = true,
                color = "class",
                healthTexture = "_GLOBAL_",
            },
            text = {
                {
                    name = "ArenaLeftText",
                    enabled = true,
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 14,
                    offsetY = -6,
                    size = 11,
                    color = "FFFFFF",
                    format = "[name:short]",
                    outline = "OUTLINE",
                    shadow = true,
                },
                {
                    name = "ArenaRightText",
                    enabled = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPRIGHT",
                    offsetX = 0,
                    offsetY = -6,
                    size = 11,
                    color = "FFFFFF",
                    format = "[spec]",
                    outline = "OUTLINE",
                    shadow = true,
                },
            },
            power = {
                enabled = true,
                anchor = "BOTTOM",
                relativePoint = "BOTTOM",
                powerTexture = "_GLOBAL_",
                height = 12,
                adjustHealthbarHeight = true,
                onlyHealer = true,
                offsetX = 0,
                offsetY = 0,
            },
            roleIcon = {
                enabled = true,
                size = 12,
                desaturate = true,
                color = "FFFFFF",
                anchor = "TOPLEFT",
                relativePoint = "TOPLEFT",
                offsetX = 1,
                offsetY = -5,
                defaultIcon = "common-button-square-gray-up",
                defaultAlpha = 0.5,
            },
            dispelIcon = {
                enabled = false,
                iconSize = 28,
                showGlow = false,
                backgroundColor = "00000088",
                borderWidth = "1",
                borderColor = "00000000",
                anchor = "BOTTOMRIGHT",
                relativePoint = "BOTTOMRIGHT",
                offsetX = -3,
                offsetY = 3,
            },
            dispelHighlight = {
                enabled = false,
                borderWidth = 4,
            },
            trinket = {
                enabled = true,
                iconSize = 34,
                borderWidth = "_GLOBAL_",
                borderColor = "_GLOBAL_",
                anchor = "TOPLEFT",
                relativePoint = "TOPRIGHT",
                offsetX = 6,
                offsetY = -2,
                showSwipe = true,
                showCooldownNumbers = true,
                cooldownDesaturate = true,
                cooldownAlpha = 0.5,
            },
            castbar = {
                enabled = true,
                anchor = "BOTTOMRIGHT",
                relativePoint = "BOTTOMLEFT",
                width = 124,
                height = 18,
                offsetX = -24,
                offsetY = 3,
                castbarTexture = "_GLOBAL_",
                showSpellName = true,
                textSize = 9,
                textPadding = 8,
                textAlignment = "LEFT",
                showIcon = false,
                iconPosition = "RIGHT",
                showCastTime = false,
                backgroundColor = "00000088",
                borderWidth = "_GLOBAL_",
                borderColor = "_GLOBAL_",
            },
            arenaTargets = {
                enabled = true,
                anchor = "RIGHT",
                relativePoint = "LEFT",
                offsetX = -4,
                offsetY = -2,
                mode = "friendly",
                indicatorWidth = 10,
                indicatorHeight = 16,
                spacing = 3,
                growDirection = "DOWN",
                maxIndicators = 3,
                borderWidth = 1,
                borderColor = "000000FF",
                containerBackgroundColor = "00000000",
            },
            auraFilters = {
                {
                    name = "ArenaPlayerBuffs",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"RAID_IN_COMBAT"},
                    excludeSubFilters = {"NOT_CANCELABLE"},
                    disableMouse = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMLEFT",
                    offsetX = 0,
                    offsetY = 2,
                    iconSize = 20,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 6,
                    perRow = 6,
                    growthX = "RIGHT",
                    growthY = "UP",
                    showSwipe = true,
                    showCooldownNumbers = false,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    placeholderIcon = "ui_abundance_aura02",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = false,
                },
                {
                    name = "ArenaDebuffs",
                    enabled = true,
                    baseFilter = "HARMFUL",
                    disableMouse = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    offsetX = 4,
                    offsetY = 2,
                    iconSize = 18,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 6,
                    perRow = 6,
                    growthX = "RIGHT",
                    growthY = "UP",
                    showSwipe = true,
                    showCooldownNumbers = false,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    placeholderIcon = "ui_abundance_aura02",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = false,
                },
                {
                    name = "ArenaCrowdControl",
                    enabled = true,
                    baseFilter = "HARMFUL",
                    subFilters = {"CROWD_CONTROL"},
                    disableMouse = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -20,
                    offsetY = 2,
                    iconSize = 36,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 1,
                    perRow = 1,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    showGlow = true,
                    glowColor = "FF0000",
                    placeholderIcon = "spell_shaman_hex",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = true,
                },
                {
                    name = "ArenaDefensives",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                    disableMouse = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -64,
                    offsetY = 2,
                    iconSize = 36,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 1,
                    perRow = 1,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    showGlow = true,
                    glowColor = "00ff98",
                    placeholderIcon = "inv_shield_04",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = true,
                },
                {
                    name = "ArenaImportantBuffs",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"IMPORTANT"},
                    excludeSubFilters = {
                        "BIG_DEFENSIVE",
                        "EXTERNAL_DEFENSIVE"
                    },
                    disableMouse = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -108,
                    offsetY = 2,
                    iconSize = 36,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 1,
                    perRow = 1,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    showGlow = true,
                    glowColor = "11aaee",
                    placeholderIcon = "spell_holy_avenginewrath",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = true,
                },
            },
            drTracker = {
                enabled = true,
                anchor = "TOPRIGHT",
                relativePoint = "TOPLEFT",
                offsetX = -150,
                offsetY = 2,
                iconSize = 36,
                spacingX = 2,
                spacingY = 2,
                maxIcons = 4,
                perRow = 4,
                growthX = "LEFT",
                growthY = "DOWN",
                showSwipe = true,
                showCooldownNumbers = true,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
                borderWidth = "_GLOBAL_",
                borderColor = "_GLOBAL_",
            },
        },
    }
end
