local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Battleground()
    return {
        friendly = {
            enabled = false,
            frameName = "zfRaidBattlegroundFriendlyContainer",
            anchor = "RIGHT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -300,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 25,
            perRow = 3,
            spacingX = 2,
            spacingY = 2,
            growthX = "LEFT",
            growthY = "DOWN",

            groupLayout = {
                enabled = false,
                orientation = "VERTICAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "RIGHT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 4,
                groupSpacingY = 4,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 88,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            showEmptySlots = true,
            emptySlotColor = "00000080",
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBattlegroundNameText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = 5,
                        size = 10,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                        maxWidthPercent = 0.80,
                    },
                    {
                        name = "RaidBattlegroundMaxHealthText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = -8,
                        size = 10,
                        color = "FFFFFF",
                        format = "[maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = false,
                },
                roleIcon = {
                    enabled = true,
                    size = 11,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 22,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 7,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                auraFilters = {
                    {
                        name = "RaidBattlegroundPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = -1,
                        offsetY = 1,
                        iconSize = 16,
                        spacingX = 1,
                        spacingY = 1,
                        maxIcons = 4,
                        perRow = 4,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },

                objectiveCarrier = {
                    enabled = true,
                    size = 20,
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
                readyCheck = {
                    enabled = true,
                    size = 16,
                    offsetX = 0,
                    offsetY = 0,
                },
            },
        },

        enemy = {
            enabled = false,
            frameName = "zfRaidBattlegroundEnemyContainer",
            anchor = "LEFT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 300,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 25,
            perRow = 3,
            spacingX = 2,
            spacingY = 2,
            growthX = "RIGHT",
            growthY = "DOWN",

            groupLayout = {
                enabled = false,
                orientation = "VERTICAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "LEFT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 4,
                groupSpacingY = 4,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 88,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBattlegroundEnemyNameText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = 5,
                        size = 10,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                        maxWidthPercent = 0.50,
                    },
                    {
                        name = "RaidBattlegroundEnemyMaxHealthText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = -8,
                        size = 10,
                        color = "FFFFFF",
                        format = "[maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = false,
                },
                roleIcon = {
                    enabled = true,
                    size = 11,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 22,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 7,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                auraFilters = {
                    {
                        name = "RaidBattlegroundEnemyBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 1,
                        offsetY = 1,
                        iconSize = 16,
                        spacingX = 1,
                        spacingY = 1,
                        maxIcons = 5,
                        perRow = 5,
                        growthX = "RIGHT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },
                objectiveCarrier = {
                    enabled = true,
                    size = 20,
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
            },
        },

        battlefieldMap = {
            enabled = true,
            opacity = 1.0,
            hideBorderFrame = true,
            borderWidth = 2,
            borderColor = "000000FF",
            height = 300,
        },

        battlegroundCallouts = {
            enabled = true,
            buttonSize = 30,
            buttons = {
                { label = "1", message = "1 incoming" },
                { label = "2", message = "2 incoming" },
                { label = "3", message = "3 incoming" },
                { label = "+", message = "Lots incoming" },
                { label = "C", message = "Clear" },
            },
        },
    }
end
