local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Blitz()
    return {
        friendly = {
            enabled = false,
            frameName = "zfRaidBlitzFriendlyContainer",
            anchor = "RIGHT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -370,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 8,
            perRow = 1,
            spacingX = 0,
            spacingY = 3,
            growthX = "LEFT",
            growthY = "DOWN",

            unitWidth = 184,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            showEmptySlots = true,
            emptySlotColor = "00000080",
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBlitzFriendlyLeftText",
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 15,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "RaidBlitzFriendlyRightText",
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = -1,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 10,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -5,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 24,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMLEFT",
                    offsetX = 3,
                    offsetY = 3,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    width = 84,
                    height = 16,
                    offsetX = 6,
                    offsetY = 3,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 8,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "BlitzFriendlyPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = 2,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 7,
                        perRow = 7,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "BlitzFriendlyDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = -2,
                        offsetY = 2,
                        iconSize = 16,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "BlitzFriendlyCrowdControl",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        subFilters = {"CROWD_CONTROL"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "FF0000",
                        placeholderIcon = "spell_shaman_hex",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                    {
                        name = "BlitzFriendlyDefensives",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 32,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "00ff98",
                        placeholderIcon = "inv_shield_04",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                    {
                        name = "BlitzFriendlyImportantBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"IMPORTANT"},
                        excludeSubFilters = {
                            "BIG_DEFENSIVE",
                            "EXTERNAL_DEFENSIVE"
                        },
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 62,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "11aaee",
                        placeholderIcon = "spell_holy_avenginewrath",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                },
                objectiveCarrier = {
                    enabled = true,
                    size = 20,
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
                readyCheck = {
                    enabled = true,
                    size = 16,
                    offsetX = 0,
                    offsetY = 0,
                },
            },
        },

        enemy = {
            enabled = false,
            frameName = "zfRaidBlitzEnemyContainer",
            anchor = "LEFT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 370,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 8,
            perRow = 1,
            spacingX = 0,
            spacingY = 3,
            growthX = "RIGHT",
            growthY = "DOWN",

            unitWidth = 184,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBlitzEnemyLeftText",
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 14,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "RaidBlitzEnemyRightText",
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 10,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = -2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 24,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMLEFT",
                    offsetX = 3,
                    offsetY = 3,
                },
                dispelHighlight = {
                    enabled = false,
                    borderWidth = 4,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMRIGHT",
                    relativePoint = "BOTTOMLEFT",
                    width = 84,
                    height = 16,
                    offsetX = -6,
                    offsetY = 3,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 8,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "BlitzEnemyPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = 2,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 7,
                        perRow = 7,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "BlitzEnemyDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 2,
                        offsetY = 2,
                        iconSize = 16,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "RIGHT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "BlitzEnemyCrowdControl",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        subFilters = {"CROWD_CONTROL"},
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -2,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "FF0000",
                        placeholderIcon = "spell_shaman_hex",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                    {
                        name = "BlitzEnemyDefensives",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -32,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "00ff98",
                        placeholderIcon = "inv_shield_04",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                    {
                        name = "BlitzEnemyImportantBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"IMPORTANT"},
                        excludeSubFilters = {
                            "BIG_DEFENSIVE",
                            "EXTERNAL_DEFENSIVE"
                        },
                        disableMouse = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -62,
                        offsetY = 2,
                        iconSize = 24,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        showGlow = true,
                        glowColor = "11aaee",
                        placeholderIcon = "spell_holy_avenginewrath",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = true,
                    },
                },
                drTracker = {
                    enabled = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -94,
                    offsetY = 2,
                    iconSize = 24,
                    spacingX = 2,
                    spacingY = 2,
                    maxIcons = 4,
                    perRow = 4,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                objectiveCarrier = {
                    enabled = true,
                    size = 20,
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
            },
        },

        battlefieldMap = {
            enabled = true,
            opacity = 1.0,
            hideBorderFrame = true,
            borderWidth = 2,
            borderColor = "000000FF",
            height = 300,
        },

        battlegroundCallouts = {
            enabled = true,
            buttonSize = 30,
            buttons = {
                { label = "1", message = "1 incoming" },
                { label = "2", message = "2 incoming" },
                { label = "3", message = "3 incoming" },
                { label = "+", message = "Lots incoming" },
                { label = "C", message = "Clear" },
            },
        },
    }
end
