local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Blitz()
    return {
        friendly = {
            enabled = false,
            frameName = "zfRaidBlitzFriendlyContainer",
            anchor = "CENTER",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -430,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 8,
            perRow = 1,
            spacingX = 0,
            spacingY = 3,
            growthX = "RIGHT",
            growthY = "DOWN",

            unitWidth = 200,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBlitzFriendlyLeftText",
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 15,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:medium]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "RaidBlitzFriendlyRightText",
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = -1,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 10,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -5,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = dispelIcon,
                    iconSize = 24,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    width = 150,
                    height = 20,
                    offsetX = 3,
                    offsetY = 3,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 8,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "RaidBlitzFriendlyBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 3,
                        offsetY = -1,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },

                readyCheck = {
                    enabled = true,
                    size = 16,
                    offsetX = 0,
                    offsetY = 0,
                },
            },
        },

        enemy = {
            enabled = false,
            frameName = "zfRaidBlitzEnemyContainer",
            anchor = "CENTER",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 430,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 8,
            perRow = 1,
            spacingX = 0,
            spacingY = 3,
            growthX = "LEFT",
            growthY = "DOWN",

            unitWidth = 200,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidBlitzEnemyLeftText",
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 1,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "RaidBlitzEnemyRightText",
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = -15,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:medium]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 10,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "RIGHT",
                    relativePoint = "RIGHT",
                    offsetX = -2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = dispelIcon,
                    iconSize = 24,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMRIGHT",
                    relativePoint = "BOTTOMLEFT",
                    width = 150,
                    height = 20,
                    offsetX = -3,
                    offsetY = 3,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 8,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "RIGHT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "RaidBlitzEnemyBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        offsetX = -3,
                        offsetY = -1,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },
            },
        },
    }
end
