local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Boss()
    return {
        enabled = false,
        hideBlizzard = false,

        frameName = "zfBossContainer",
        anchor = "LEFT",
        relativeTo = "UIParent",
        relativePoint = "CENTER",
        offsetX = 370,
        offsetY = 0,
        containerBackgroundColor = "00000000",
        containerBorderWidth = 0,
        containerBorderColor = "00000000",

        maxUnits = 5,
        perRow = 1,
        spacingX = 0,
        spacingY = 3,
        growthX = "LEFT",
        growthY = "DOWN",

        unitWidth = 150,
        unitHeight = 60,
        unitBackgroundColor = "00000088",
        borderWidth = "_GLOBAL_",
        borderColor = "_GLOBAL_",
        highlightSelected = true,

        leftClick = "select",
        rightClick = "contextMenu",
        hideInArena = false,

        modules = {
            health = {
                enabled = true,
                color = "class",
                healthTexture = "_GLOBAL_",
            },
            text = {
                {
                    name = "BossLeftText",
                    enabled = true,
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 14,
                    offsetY = -6,
                    size = 11,
                    color = "FFFFFF",
                    format = "[name:short]",
                    outline = "OUTLINE",
                    shadow = true,
                },
                {
                    name = "BossRightText",
                    enabled = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPRIGHT",
                    offsetX = 0,
                    offsetY = -6,
                    size = 11,
                    color = "FFFFFF",
                    format = "[spec]",
                    outline = "OUTLINE",
                    shadow = true,
                },
            },
            power = {
                enabled = true,
                anchor = "BOTTOM",
                relativePoint = "BOTTOM",
                powerTexture = "_GLOBAL_",
                height = 12,
                adjustHealthbarHeight = true,
                onlyHealer = false,
                offsetX = 0,
                offsetY = 0,
            },
            dispelIcon = {
                enabled = false,
                iconSize = 28,
                showGlow = false,
                backgroundColor = "00000088",
                borderWidth = "1",
                borderColor = "00000000",
                anchor = "BOTTOMRIGHT",
                relativePoint = "BOTTOMRIGHT",
                offsetX = -3,
                offsetY = 3,
            },
            dispelHighlight = {
                enabled = true,
                borderWidth = 4,
            },
            castbar = {
                enabled = true,
                anchor = "BOTTOMRIGHT",
                relativePoint = "BOTTOMLEFT",
                width = 124,
                height = 18,
                offsetX = -24,
                offsetY = 3,
                castbarTexture = "_GLOBAL_",
                showSpellName = true,
                textSize = 9,
                textPadding = 8,
                textAlignment = "LEFT",
                showIcon = false,
                iconPosition = "RIGHT",
                showCastTime = false,
                backgroundColor = "00000088",
                borderWidth = "_GLOBAL_",
                borderColor = "_GLOBAL_",
            },
            auraFilters = {
                {
                    name = "BossBuffs",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"RAID_IN_COMBAT"},
                    excludeSubFilters = {"NOT_CANCELABLE"},
                    disableMouse = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMLEFT",
                    offsetX = 0,
                    offsetY = 2,
                    iconSize = 20,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 6,
                    perRow = 6,
                    growthX = "RIGHT",
                    growthY = "UP",
                    showSwipe = true,
                    showCooldownNumbers = false,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    placeholderIcon = "ui_abundance_aura02",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = false,
                },
                {
                    name = "BossDebuffs",
                    enabled = true,
                    baseFilter = "HARMFUL",
                    disableMouse = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    offsetX = 4,
                    offsetY = 2,
                    iconSize = 18,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 6,
                    perRow = 6,
                    growthX = "RIGHT",
                    growthY = "UP",
                    showSwipe = true,
                    showCooldownNumbers = false,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    placeholderIcon = "ui_abundance_aura02",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = false,
                },
                {
                    name = "BossDefensives",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                    disableMouse = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -24,
                    offsetY = 2,
                    iconSize = 36,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 1,
                    perRow = 1,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    showGlow = true,
                    glowColor = "00ff98",
                    placeholderIcon = "inv_shield_04",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = true,
                },
                {
                    name = "BossImportantBuffs",
                    enabled = true,
                    baseFilter = "HELPFUL",
                    subFilters = {"IMPORTANT"},
                    excludeSubFilters = {
                        "BIG_DEFENSIVE",
                        "EXTERNAL_DEFENSIVE"
                    },
                    disableMouse = true,
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -68,
                    offsetY = 2,
                    iconSize = 36,
                    spacingX = 2,
                    spacingY = 0,
                    maxIcons = 1,
                    perRow = 1,
                    growthX = "LEFT",
                    growthY = "DOWN",
                    showSwipe = true,
                    showCooldownNumbers = true,
                    tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                    containerBackgroundColor = "00000000",
                    containerBorderWidth = 0,
                    containerBorderColor = "00000000",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                    showGlow = true,
                    glowColor = "11aaee",
                    placeholderIcon = "spell_holy_avenginewrath",
                    placeholderDesaturate = true,
                    placeholderColor = "FFFFFF88",
                    showPlaceholderIcon = true,
                },
            },
        },
    }
end
