local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_EpicBattleground()
    return {
        friendly = {
            enabled = true,
            frameName = "zfRaidEpicFriendlyContainer",
            anchor = "RIGHT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -300,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 40,
            perRow = 5,
            spacingX = 2,
            spacingY = 2,
            growthX = "LEFT",
            growthY = "DOWN",

            groupLayout = {
                enabled = false,
                orientation = "VERTICAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "RIGHT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 4,
                groupSpacingY = 4,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 70,
            unitHeight = 40,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidEpicBattlegroundNameText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = 7,
                        size = 10,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                        maxWidth = 0.80,
                    },
                    {
                        name = "RaidEpicBattlegroundHealthText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = -7,
                        size = 10,
                        color = "FFFFFF",
                        format = "[curhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = false,
                },
                roleIcon = {
                    enabled = true,
                    size = 11,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 22,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 7,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                auraFilters = {
                    {
                        name = "RaidEpicBattlegroundPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = -1,
                        offsetY = 1,
                        iconSize = 10,
                        spacingX = 1,
                        spacingY = 1,
                        maxIcons = 4,
                        perRow = 4,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },

                readyCheck = {
                    enabled = true,
                    size = 16,
                    offsetX = 0,
                    offsetY = 0,
                },
                objectiveIcon = {
                    enabled = true,
                    iconSize = 24,
                    backgroundColor = "00000000",
                    borderWidth = 1,
                    borderColor = "00000000",
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
            },
        },

        enemy = {
            enabled = true,
            frameName = "zfRaidEpicEnemyContainer",
            anchor = "LEFT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 300,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 40,
            perRow = 5,
            spacingX = 2,
            spacingY = 2,
            growthX = "LEFT",
            growthY = "DOWN",

            groupLayout = {
                enabled = false,
                orientation = "VERTICAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "LEFT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 4,
                groupSpacingY = 4,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 70,
            unitHeight = 40,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidEpicBattlegroundEnemyNameText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = 7,
                        size = 10,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                        maxWidth = 0.80,
                    },
                    {
                        name = "RaidEpicBattlegroundEnemyHealthText",
                        enabled = true,
                        anchor = "CENTER",
                        relativePoint = "CENTER",
                        offsetX = 0,
                        offsetY = -7,
                        size = 10,
                        color = "FFFFFF",
                        format = "[curhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = false,
                },
                roleIcon = {
                    enabled = true,
                    size = 11,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 22,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 7,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                auraFilters = {
                    {
                        name = "RaidEpicBattlegroundEnemyBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "BOTTOMLEFT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 1,
                        offsetY = 1,
                        iconSize = 10,
                        spacingX = 1,
                        spacingY = 1,
                        maxIcons = 4,
                        perRow = 4,
                        growthX = "RIGHT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMRIGHT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },
                objectiveIcon = {
                    enabled = true,
                    iconSize = 24,
                    backgroundColor = "00000000",
                    borderWidth = 1,
                    borderColor = "00000000",
                    anchor = "TOP",
                    relativePoint = "TOP",
                    offsetX = 0,
                    offsetY = -2,
                },
            },
        },
        callIncs = {
            enabled = true,
            buttonSize = 30,
            buttons = {
                { label = "1", message = "$zone: 1 inc" },
                { label = "2", message = "$zone: 2 inc" },
                { label = "3", message = "$zone: 3 inc" },
                { label = "+", message = "$zone: Lots inc" },
                { label = "C", message = "$zone: Clear" },
            },
        },
    }
end
