local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_EpicBattleground()
    return {
        friendly = {
            enabled = false,
            frameName = "zfRaidEpicFriendlyContainer",
            anchor = "CENTER",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -430,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 40,
            perRow = 5,
            spacingX = 1,
            spacingY = 1,
            growthX = "RIGHT",
            growthY = "DOWN",

            groupLayout = {
                enabled = true,
                orientation = "HORIZONTAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "RIGHT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 1,
                groupSpacingY = 1,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 50,
            unitHeight = 35,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                roleIcon = {
                    enabled = true,
                    size = 10,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 1,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 16,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                readyCheck = {
                    enabled = true,
                    size = 14,
                    offsetX = 0,
                    offsetY = 0,
                },
            },
        },

        enemy = {
            enabled = false,
            frameName = "zfRaidEpicEnemyContainer",
            anchor = "CENTER",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = 430,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 40,
            perRow = 5,
            spacingX = 1,
            spacingY = 1,
            growthX = "LEFT",
            growthY = "DOWN",

            groupLayout = {
                enabled = true,
                orientation = "HORIZONTAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "LEFT",
                overrideGrowthY = "DOWN",
                showGroupLabels = false,
                groupLabelFormat = "[group]",
                groupLabelSize = 10,
                groupSpacingX = 1,
                groupSpacingY = 1,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 50,
            unitHeight = 35,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                roleIcon = {
                    enabled = true,
                    size = 10,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "RIGHT",
                    relativePoint = "RIGHT",
                    offsetX = -1,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = false,
                    iconSize = 16,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
            },
        },
    }
end
