local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Extras()
    return {
        waypoints = {
            enabled = true,
        },
        info = {
            enabled = true,
        },
        clock = {
            enabled = true,
            fontSize = 18,
            offsetX = 0,
            offsetY = -30,
            compartmentSpacing = 15,
            showInZones = { "arena", "battleground", "dungeon", "raid", "world" },
        },
        chat = {
            enabled = true,
            unclampFrames = true,
            repositionEditBox = true,
            editBoxBackgroundOpacity = 1.0,
            hideChannelButton = true,
            hideQuickJoinToastButton = true,
            disableChatInArena = true,
        },
        spellAssistGlow = {
            enabled = true,
            glowScale = 1.4,
            glowColor = "00FF98FF",
            animationDuration = 1,
            viewerFrameName = "BuffIconCooldownViewer",
        },
        battlefieldMap = {
            enabled = true,
            opacity = 1.0,
            hideBorderFrame = true,
            borderWidth = 2,
            borderColor = "000000FF",
            height = 300,
            showInZones = { "battleground" },
        },
        minimap = {
            enabled = true,
            size = 300,
            squareMask = true,
            unclamp = true,
            borderWidth = 2,
            borderColor = "000000FF",
            hideBackdrop = true,
            hideBorderTop = true,
            hideTracking = true,
            hideZoneText = true,
            hideGameTime = true,
            hideZoomButtons = true,
            restoreAfterCutscene = true,
            showInZones = { "arena", "battleground", "dungeon", "raid", "world" },
        },
        minimapAddonIcons = {
            enabled = true,
            size = 25,
            anchorPoint = "LEFT",
            attachTo = "AddonCompartmentFrame",
            attachPoint = "RIGHT",
            spacing = 10,
            offsetX = 10,
            offsetY = 0,
        },
        questIcon = {
            enabled = true,
            atlas = "Crosshair_Quest_96",
            size = 30,
            offsetX = 17,
            offsetY = -6,
        },
        playerMarkers = {
            enabled = true,
            enabledInArena = true,
            enabledInBattleground = true,
            enabledInWorld = true,
            friendlyMarkers = {
                enabled = true,
                classIcon = false,
                specIcon = false,
                markerTexture = "CovenantSanctum-Renown-DoubleArrow",
                markerSize = 150,
                markerVerticalOffset = -20,
                markerWidth = 0,
                showHealthBars = false,
                customNameSize = 22,
                highlightTarget = true,
                highlightScale = 1.25,
                healerTexture = "none",
            },
            enemyMarkers = {
                enabled = true,
                healerTexture = "UI-LFG-RoleIcon-Healer",
                markerSize = 90,
                markerVerticalOffset = -20,
            },
        },
        actionBars = {
            enabled = true,
            borderWidth = 2,
            borderColor = "000000FF",
            buttonPadding = 0,
            iconZoom = 0.3,
            hideProcGlow = true,
            hideSpellActivationOverlay = true,
            hideMacroText = true,
            hideKeybindText = true,
            hideSpellCastAnim = true,
            addBarBackgrounds = true,
            barBackgroundOpacity = 0.5,
            customizeAssistedHighlight = true,
            assistedHighlightColor = "FF00FFFF",
            fadeBars = {
                actionBar2 = false,
                actionBar3 = true,
                actionBar4 = true,
                actionBar5 = true,
                actionBar6 = true,
                actionBar7 = true,
                actionBar8 = true,
                petBar = false,
                stanceBar = false,
            },
        },
        microMenu = {
            enabled = true,
            showInZones = {},
        },
        bagsBar = {
            enabled = true,
            showInZones = {},
        },
        questFrame = {
            enabled = true,
            showInZones = {},
        },
        statusBar = {
            enabled = true,
            showInZones = {},
        },
        dungeonFinderEye = {
            enabled = true,
            size = 30,
            anchorPoint = "RIGHT",
            attachTo = "TimeManagerClockButton",
            attachPoint = "LEFT",
            offsetX = -10,
            offsetY = 1,
        },
        battlegroundCallouts = {
            enabled = true,
            isPvP = true,
            buttonSize = 30,
            buttons = {
                { label = "1", message = "1 incoming" },
                { label = "2", message = "2 incoming" },
                { label = "3", message = "3 incoming" },
                { label = "+", message = "Lots incoming" },
                { label = "C", message = "Clear" },
            },
        },
    }
end
