local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Raid()
    return {
        friendly = {
            enabled = false,
            frameName = "zfRaidPveFriendlyContainer",
            anchor = "CENTER",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -430,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            maxUnits = 40,
            perRow = 5,
            spacingX = 2,
            spacingY = 2,
            growthX = "RIGHT",
            growthY = "DOWN",

            groupLayout = {
                enabled = true,
                orientation = "HORIZONTAL",
                unitsPerGroup = 5,
                enforcePerRow = 5,
                overrideGrowthX = "RIGHT",
                overrideGrowthY = "DOWN",
                showGroupLabels = true,
                groupLabelFormat = "Group [group]",
                groupLabelSize = 10,
                groupSpacingX = 4,
                groupSpacingY = 4,
                containerBackgroundColor = "00000000",
                containerBorderWidth = 0,
                containerBorderColor = "00000000",
            },

            unitWidth = 100,
            unitHeight = 50,
            unitBackgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            outOfRangeOpacity = "_GLOBAL_",
            highlightSelected = true,
            leftClick = "select",
            rightClick = "contextMenu",

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "RaidPveNameText",
                        enabled = true,
                        anchor = "TOP",
                        relativePoint = "TOP",
                        offsetX = 0,
                        offsetY = -3,
                        size = 10,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = false,
                },
                roleIcon = {
                    enabled = true,
                    size = 11,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "LEFT",
                    relativePoint = "LEFT",
                    offsetX = 2,
                    offsetY = 0,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelIcon = {
                    enabled = dispelIcon,
                    iconSize = 22,
                    showGlow = false,
                    backgroundColor = "00000088",
                    borderWidth = "1",
                    borderColor = "00000000",
                    anchor = "CENTER",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 7,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                auraFilters = {
                    {
                        name = "RaidPvePlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        clickThrough = true,
                        disableMouse = true,
                        disableTooltip = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = -1,
                        offsetY = 1,
                        iconSize = 20,
                        spacingX = 1,
                        spacingY = 1,
                        maxIcons = 4,
                        perRow = 4,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },

                readyCheck = {
                    enabled = true,
                    size = 16,
                    offsetX = 0,
                    offsetY = 0,
                },
            },
        },
    }
end
