local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetDefaultConfig_Units()
    return {
        player = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfPlayerFrame",
            anchor = "TOPRIGHT",
            relativeTo = "UIParent",
            relativePoint = "BOTTOM",
            offsetX = -178,
            offsetY = 163,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "select",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    frameName = "zfPlayerHealthbar",
                    anchor = "TOP",
                    relativeTo = "zfPlayerFrame",
                    relativePoint = "TOP",
                    healthTexture = "_GLOBAL_",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        name = "PlayerLeftText",
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "zfPlayerFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "PlayerRightText",
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "zfPlayerFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    frameName = "zfPlayerPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "zfPlayerFrame",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                castbar = {
                    enabled = true,
                    frameName = "zfPlayerCastbar",
                    anchor = "BOTTOM",
                    relativeTo = "MainActionBar",
                    relativePoint = "TOP",
                    width = 332,
                    height = 30,
                    offsetX = 0,
                    offsetY = 10,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 12,
                    textPadding = 8,
                    textAlignment = "CENTER",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "StaticPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        disableMouse = false,
                        frameName = "zfStaticPlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = -100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "ActivePlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = false,
                        frameName = "zfActivePlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "zfStaticPlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "ActivePlayerDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "zfActivePlayerDebuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "zfActivePlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    absorbTexture = "_GLOBAL_",
                },
                combatIndicator = {
                    enabled = true,
                    atlasTexture = "titleprestige-prestigeicon",
                    size = 30,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
                restingIndicator = {
                    enabled = true,
                    atlasTexture = "plunderstorm-nameplates-icon-2",
                    size = 36,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
            },
        },
        target = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "UIParent",
            relativePoint = "BOTTOM",
            offsetX = 178,
            offsetY = 163,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "inspect",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    frameName = "zfTargetHealth",
                    anchor = "TOP",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "TOP",
                    healthTexture = "_GLOBAL_",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        name = "TargetLeftText",
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "zfTargetFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                    {
                        name = "TargetRightText",
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "zfTargetFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
                power = {
                    enabled = true,
                    frameName = "zfTargetPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "BOTTOM",
                    powerTexture = "_GLOBAL_",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                },
                castbar = {
                    enabled = true,
                    frameName = "zfTargetCastbar",
                    anchor = "TOP",
                    relativeTo = "zfTargetFrame",
                    relativePoint = "BOTTOM",
                    height = 20,
                    offsetX = 0,
                    offsetY = 0,
                    castbarTexture = "_GLOBAL_",
                    showSpellName = true,
                    textSize = 12,
                    textPadding = 8,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "RIGHT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = "_GLOBAL_",
                    borderColor = "_GLOBAL_",
                },
                auraFilters = {
                    {
                        name = "StaticTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        disableMouse = false,
                        frameName = "zfStaticTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = 100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "ActiveTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = false,
                        frameName = "zfActiveTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "zfStaticTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                    {
                        name = "ActiveTargetDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "zfActiveTargetDebuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "zfActiveTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        borderWidth = "_GLOBAL_",
                        borderColor = "_GLOBAL_",
                        placeholderIcon = "ui_abundance_aura02",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88",
                        showPlaceholderIcon = false,
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    absorbTexture = "_GLOBAL_",
                },
            },
        },
        targetTarget = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfTargetTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfTargetFrame",
            relativePoint = "TOPRIGHT",
            offsetX = 10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "select",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "TargetTargetText",
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfTargetTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
            },
        },
        focus = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfFocusFrame",
            anchor = "TOPRIGHT",
            relativeTo = "zfPlayerFrame",
            relativePoint = "TOPLEFT",
            offsetX = -10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "select",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "FocusText",
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfFocusFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
            },
        },
        focusTarget = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfFocusTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfFocusFrame",
            relativePoint = "BOTTOMLEFT",
            offsetX = 0,
            offsetY = 0,
            width = 75,
            height = 20,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "select",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "FocusTargetText",
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "zfFocusTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
            },
        },
        pet = {
            enabled = true,
            hideBlizzard = false,
            frameName = "zfPetFrame",
            anchor = "TOPLEFT",
            relativeTo = "zfPlayerFrame",
            relativePoint = "BOTTOMLEFT",
            offsetX = 0,
            offsetY = -15,
            width = 93,
            height = 29,
            backgroundColor = "00000088",
            borderWidth = "_GLOBAL_",
            borderColor = "_GLOBAL_",
            leftClick = "select",
            rightClick = "contextMenu",
            hideInArena = false,

            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    healthTexture = "_GLOBAL_",
                },
                text = {
                    {
                        name = "PetText",
                        enabled = true,
                        anchor = "CENTER",
                        relativeTo = "zfPetFrame",
                        relativePoint = "CENTER",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                        outline = "OUTLINE",
                        shadow = true,
                    },
                },
            },
        },
    }
end
